// Code generated by go-swagger; DO NOT EDIT.

package checkpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/damoun/uptrends/models"
)

// CheckpointGetAllCheckpointsReader is a Reader for the CheckpointGetAllCheckpoints structure.
type CheckpointGetAllCheckpointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckpointGetAllCheckpointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckpointGetAllCheckpointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCheckpointGetAllCheckpointsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCheckpointGetAllCheckpointsOK creates a CheckpointGetAllCheckpointsOK with default headers values
func NewCheckpointGetAllCheckpointsOK() *CheckpointGetAllCheckpointsOK {
	return &CheckpointGetAllCheckpointsOK{}
}

/*CheckpointGetAllCheckpointsOK handles this case with default header values.

List of checkpoints
*/
type CheckpointGetAllCheckpointsOK struct {
	Payload *models.CheckpointListResponse
}

func (o *CheckpointGetAllCheckpointsOK) Error() string {
	return fmt.Sprintf("[GET /Checkpoint][%d] checkpointGetAllCheckpointsOK  %+v", 200, o.Payload)
}

func (o *CheckpointGetAllCheckpointsOK) GetPayload() *models.CheckpointListResponse {
	return o.Payload
}

func (o *CheckpointGetAllCheckpointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CheckpointListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckpointGetAllCheckpointsBadRequest creates a CheckpointGetAllCheckpointsBadRequest with default headers values
func NewCheckpointGetAllCheckpointsBadRequest() *CheckpointGetAllCheckpointsBadRequest {
	return &CheckpointGetAllCheckpointsBadRequest{}
}

/*CheckpointGetAllCheckpointsBadRequest handles this case with default header values.

The request failed.
*/
type CheckpointGetAllCheckpointsBadRequest struct {
	Payload *models.APIMessageInfo
}

func (o *CheckpointGetAllCheckpointsBadRequest) Error() string {
	return fmt.Sprintf("[GET /Checkpoint][%d] checkpointGetAllCheckpointsBadRequest  %+v", 400, o.Payload)
}

func (o *CheckpointGetAllCheckpointsBadRequest) GetPayload() *models.APIMessageInfo {
	return o.Payload
}

func (o *CheckpointGetAllCheckpointsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMessageInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
