// Code generated by go-swagger; DO NOT EDIT.

package vault

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVaultGetAllVaultSectionsParams creates a new VaultGetAllVaultSectionsParams object
// with the default values initialized.
func NewVaultGetAllVaultSectionsParams() *VaultGetAllVaultSectionsParams {

	return &VaultGetAllVaultSectionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVaultGetAllVaultSectionsParamsWithTimeout creates a new VaultGetAllVaultSectionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVaultGetAllVaultSectionsParamsWithTimeout(timeout time.Duration) *VaultGetAllVaultSectionsParams {

	return &VaultGetAllVaultSectionsParams{

		timeout: timeout,
	}
}

// NewVaultGetAllVaultSectionsParamsWithContext creates a new VaultGetAllVaultSectionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewVaultGetAllVaultSectionsParamsWithContext(ctx context.Context) *VaultGetAllVaultSectionsParams {

	return &VaultGetAllVaultSectionsParams{

		Context: ctx,
	}
}

// NewVaultGetAllVaultSectionsParamsWithHTTPClient creates a new VaultGetAllVaultSectionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVaultGetAllVaultSectionsParamsWithHTTPClient(client *http.Client) *VaultGetAllVaultSectionsParams {

	return &VaultGetAllVaultSectionsParams{
		HTTPClient: client,
	}
}

/*VaultGetAllVaultSectionsParams contains all the parameters to send to the API endpoint
for the vault get all vault sections operation typically these are written to a http.Request
*/
type VaultGetAllVaultSectionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the vault get all vault sections params
func (o *VaultGetAllVaultSectionsParams) WithTimeout(timeout time.Duration) *VaultGetAllVaultSectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vault get all vault sections params
func (o *VaultGetAllVaultSectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vault get all vault sections params
func (o *VaultGetAllVaultSectionsParams) WithContext(ctx context.Context) *VaultGetAllVaultSectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vault get all vault sections params
func (o *VaultGetAllVaultSectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vault get all vault sections params
func (o *VaultGetAllVaultSectionsParams) WithHTTPClient(client *http.Client) *VaultGetAllVaultSectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vault get all vault sections params
func (o *VaultGetAllVaultSectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *VaultGetAllVaultSectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
