// Code generated by go-swagger; DO NOT EDIT.

package vault

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVaultDeleteAuthorizationForVaultSectionParams creates a new VaultDeleteAuthorizationForVaultSectionParams object
// with the default values initialized.
func NewVaultDeleteAuthorizationForVaultSectionParams() *VaultDeleteAuthorizationForVaultSectionParams {
	var ()
	return &VaultDeleteAuthorizationForVaultSectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVaultDeleteAuthorizationForVaultSectionParamsWithTimeout creates a new VaultDeleteAuthorizationForVaultSectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVaultDeleteAuthorizationForVaultSectionParamsWithTimeout(timeout time.Duration) *VaultDeleteAuthorizationForVaultSectionParams {
	var ()
	return &VaultDeleteAuthorizationForVaultSectionParams{

		timeout: timeout,
	}
}

// NewVaultDeleteAuthorizationForVaultSectionParamsWithContext creates a new VaultDeleteAuthorizationForVaultSectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewVaultDeleteAuthorizationForVaultSectionParamsWithContext(ctx context.Context) *VaultDeleteAuthorizationForVaultSectionParams {
	var ()
	return &VaultDeleteAuthorizationForVaultSectionParams{

		Context: ctx,
	}
}

// NewVaultDeleteAuthorizationForVaultSectionParamsWithHTTPClient creates a new VaultDeleteAuthorizationForVaultSectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVaultDeleteAuthorizationForVaultSectionParamsWithHTTPClient(client *http.Client) *VaultDeleteAuthorizationForVaultSectionParams {
	var ()
	return &VaultDeleteAuthorizationForVaultSectionParams{
		HTTPClient: client,
	}
}

/*VaultDeleteAuthorizationForVaultSectionParams contains all the parameters to send to the API endpoint
for the vault delete authorization for vault section operation typically these are written to a http.Request
*/
type VaultDeleteAuthorizationForVaultSectionParams struct {

	/*AuthorizationGUID
	  The Guid of the authorization that should be deleted.

	*/
	AuthorizationGUID string
	/*VaultSectionGUID
	  The Guid of the vault section for which the authorization should be deleted.

	*/
	VaultSectionGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) WithTimeout(timeout time.Duration) *VaultDeleteAuthorizationForVaultSectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) WithContext(ctx context.Context) *VaultDeleteAuthorizationForVaultSectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) WithHTTPClient(client *http.Client) *VaultDeleteAuthorizationForVaultSectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorizationGUID adds the authorizationGUID to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) WithAuthorizationGUID(authorizationGUID string) *VaultDeleteAuthorizationForVaultSectionParams {
	o.SetAuthorizationGUID(authorizationGUID)
	return o
}

// SetAuthorizationGUID adds the authorizationGuid to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) SetAuthorizationGUID(authorizationGUID string) {
	o.AuthorizationGUID = authorizationGUID
}

// WithVaultSectionGUID adds the vaultSectionGUID to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) WithVaultSectionGUID(vaultSectionGUID string) *VaultDeleteAuthorizationForVaultSectionParams {
	o.SetVaultSectionGUID(vaultSectionGUID)
	return o
}

// SetVaultSectionGUID adds the vaultSectionGuid to the vault delete authorization for vault section params
func (o *VaultDeleteAuthorizationForVaultSectionParams) SetVaultSectionGUID(vaultSectionGUID string) {
	o.VaultSectionGUID = vaultSectionGUID
}

// WriteToRequest writes these params to a swagger request
func (o *VaultDeleteAuthorizationForVaultSectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param authorizationGuid
	if err := r.SetPathParam("authorizationGuid", o.AuthorizationGUID); err != nil {
		return err
	}

	// path param vaultSectionGuid
	if err := r.SetPathParam("vaultSectionGuid", o.VaultSectionGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
