// Code generated by go-swagger; DO NOT EDIT.

package vault

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/damoun/uptrends/v4/models"
)

// NewVaultUpdateVaultItemParams creates a new VaultUpdateVaultItemParams object
// with the default values initialized.
func NewVaultUpdateVaultItemParams() *VaultUpdateVaultItemParams {
	var ()
	return &VaultUpdateVaultItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVaultUpdateVaultItemParamsWithTimeout creates a new VaultUpdateVaultItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVaultUpdateVaultItemParamsWithTimeout(timeout time.Duration) *VaultUpdateVaultItemParams {
	var ()
	return &VaultUpdateVaultItemParams{

		timeout: timeout,
	}
}

// NewVaultUpdateVaultItemParamsWithContext creates a new VaultUpdateVaultItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewVaultUpdateVaultItemParamsWithContext(ctx context.Context) *VaultUpdateVaultItemParams {
	var ()
	return &VaultUpdateVaultItemParams{

		Context: ctx,
	}
}

// NewVaultUpdateVaultItemParamsWithHTTPClient creates a new VaultUpdateVaultItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVaultUpdateVaultItemParamsWithHTTPClient(client *http.Client) *VaultUpdateVaultItemParams {
	var ()
	return &VaultUpdateVaultItemParams{
		HTTPClient: client,
	}
}

/*VaultUpdateVaultItemParams contains all the parameters to send to the API endpoint
for the vault update vault item operation typically these are written to a http.Request
*/
type VaultUpdateVaultItemParams struct {

	/*Item
	  The complete definition of the vault item that should be updated.

	*/
	Item *models.VaultItem
	/*VaultItemGUID
	  The Guid of the vault item that should be updated.

	*/
	VaultItemGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the vault update vault item params
func (o *VaultUpdateVaultItemParams) WithTimeout(timeout time.Duration) *VaultUpdateVaultItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vault update vault item params
func (o *VaultUpdateVaultItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vault update vault item params
func (o *VaultUpdateVaultItemParams) WithContext(ctx context.Context) *VaultUpdateVaultItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vault update vault item params
func (o *VaultUpdateVaultItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vault update vault item params
func (o *VaultUpdateVaultItemParams) WithHTTPClient(client *http.Client) *VaultUpdateVaultItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vault update vault item params
func (o *VaultUpdateVaultItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithItem adds the item to the vault update vault item params
func (o *VaultUpdateVaultItemParams) WithItem(item *models.VaultItem) *VaultUpdateVaultItemParams {
	o.SetItem(item)
	return o
}

// SetItem adds the item to the vault update vault item params
func (o *VaultUpdateVaultItemParams) SetItem(item *models.VaultItem) {
	o.Item = item
}

// WithVaultItemGUID adds the vaultItemGUID to the vault update vault item params
func (o *VaultUpdateVaultItemParams) WithVaultItemGUID(vaultItemGUID string) *VaultUpdateVaultItemParams {
	o.SetVaultItemGUID(vaultItemGUID)
	return o
}

// SetVaultItemGUID adds the vaultItemGuid to the vault update vault item params
func (o *VaultUpdateVaultItemParams) SetVaultItemGUID(vaultItemGUID string) {
	o.VaultItemGUID = vaultItemGUID
}

// WriteToRequest writes these params to a swagger request
func (o *VaultUpdateVaultItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Item != nil {
		if err := r.SetBodyParam(o.Item); err != nil {
			return err
		}
	}

	// path param vaultItemGuid
	if err := r.SetPathParam("vaultItemGuid", o.VaultItemGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
