// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// RegisterPostReader is a Reader for the RegisterPost structure.
type RegisterPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRegisterPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRegisterPostCreated creates a RegisterPostCreated with default headers values
func NewRegisterPostCreated() *RegisterPostCreated {
	return &RegisterPostCreated{}
}

/*RegisterPostCreated handles this case with default header values.

If you get this response, a new API account was created successfully.
*/
type RegisterPostCreated struct {
	Payload *models.RegistrationResponse
}

func (o *RegisterPostCreated) Error() string {
	return fmt.Sprintf("[POST /Register][%d] registerPostCreated  %+v", 201, o.Payload)
}

func (o *RegisterPostCreated) GetPayload() *models.RegistrationResponse {
	return o.Payload
}

func (o *RegisterPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegistrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
