// Code generated by go-swagger; DO NOT EDIT.

package statistics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// StatisticsGetMonitorStatisticsReader is a Reader for the StatisticsGetMonitorStatistics structure.
type StatisticsGetMonitorStatisticsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatisticsGetMonitorStatisticsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStatisticsGetMonitorStatisticsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStatisticsGetMonitorStatisticsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewStatisticsGetMonitorStatisticsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStatisticsGetMonitorStatisticsOK creates a StatisticsGetMonitorStatisticsOK with default headers values
func NewStatisticsGetMonitorStatisticsOK() *StatisticsGetMonitorStatisticsOK {
	return &StatisticsGetMonitorStatisticsOK{}
}

/*StatisticsGetMonitorStatisticsOK handles this case with default header values.

The request completed successfully.
*/
type StatisticsGetMonitorStatisticsOK struct {
	Payload *models.StatisticsResponse
}

func (o *StatisticsGetMonitorStatisticsOK) Error() string {
	return fmt.Sprintf("[GET /Statistics/Monitor/{monitorGuid}][%d] statisticsGetMonitorStatisticsOK  %+v", 200, o.Payload)
}

func (o *StatisticsGetMonitorStatisticsOK) GetPayload() *models.StatisticsResponse {
	return o.Payload
}

func (o *StatisticsGetMonitorStatisticsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatisticsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStatisticsGetMonitorStatisticsBadRequest creates a StatisticsGetMonitorStatisticsBadRequest with default headers values
func NewStatisticsGetMonitorStatisticsBadRequest() *StatisticsGetMonitorStatisticsBadRequest {
	return &StatisticsGetMonitorStatisticsBadRequest{}
}

/*StatisticsGetMonitorStatisticsBadRequest handles this case with default header values.

The request failed.
*/
type StatisticsGetMonitorStatisticsBadRequest struct {
	Payload *models.MessageInfo
}

func (o *StatisticsGetMonitorStatisticsBadRequest) Error() string {
	return fmt.Sprintf("[GET /Statistics/Monitor/{monitorGuid}][%d] statisticsGetMonitorStatisticsBadRequest  %+v", 400, o.Payload)
}

func (o *StatisticsGetMonitorStatisticsBadRequest) GetPayload() *models.MessageInfo {
	return o.Payload
}

func (o *StatisticsGetMonitorStatisticsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStatisticsGetMonitorStatisticsNotFound creates a StatisticsGetMonitorStatisticsNotFound with default headers values
func NewStatisticsGetMonitorStatisticsNotFound() *StatisticsGetMonitorStatisticsNotFound {
	return &StatisticsGetMonitorStatisticsNotFound{}
}

/*StatisticsGetMonitorStatisticsNotFound handles this case with default header values.

The monitor could not be found.
*/
type StatisticsGetMonitorStatisticsNotFound struct {
	Payload *models.MessageInfo
}

func (o *StatisticsGetMonitorStatisticsNotFound) Error() string {
	return fmt.Sprintf("[GET /Statistics/Monitor/{monitorGuid}][%d] statisticsGetMonitorStatisticsNotFound  %+v", 404, o.Payload)
}

func (o *StatisticsGetMonitorStatisticsNotFound) GetPayload() *models.MessageInfo {
	return o.Payload
}

func (o *StatisticsGetMonitorStatisticsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
