// Code generated by go-swagger; DO NOT EDIT.

package alert_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAlertDefinitionGetEscalationLevelIntegrationParams creates a new AlertDefinitionGetEscalationLevelIntegrationParams object
// with the default values initialized.
func NewAlertDefinitionGetEscalationLevelIntegrationParams() *AlertDefinitionGetEscalationLevelIntegrationParams {
	var ()
	return &AlertDefinitionGetEscalationLevelIntegrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAlertDefinitionGetEscalationLevelIntegrationParamsWithTimeout creates a new AlertDefinitionGetEscalationLevelIntegrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAlertDefinitionGetEscalationLevelIntegrationParamsWithTimeout(timeout time.Duration) *AlertDefinitionGetEscalationLevelIntegrationParams {
	var ()
	return &AlertDefinitionGetEscalationLevelIntegrationParams{

		timeout: timeout,
	}
}

// NewAlertDefinitionGetEscalationLevelIntegrationParamsWithContext creates a new AlertDefinitionGetEscalationLevelIntegrationParams object
// with the default values initialized, and the ability to set a context for a request
func NewAlertDefinitionGetEscalationLevelIntegrationParamsWithContext(ctx context.Context) *AlertDefinitionGetEscalationLevelIntegrationParams {
	var ()
	return &AlertDefinitionGetEscalationLevelIntegrationParams{

		Context: ctx,
	}
}

// NewAlertDefinitionGetEscalationLevelIntegrationParamsWithHTTPClient creates a new AlertDefinitionGetEscalationLevelIntegrationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAlertDefinitionGetEscalationLevelIntegrationParamsWithHTTPClient(client *http.Client) *AlertDefinitionGetEscalationLevelIntegrationParams {
	var ()
	return &AlertDefinitionGetEscalationLevelIntegrationParams{
		HTTPClient: client,
	}
}

/*AlertDefinitionGetEscalationLevelIntegrationParams contains all the parameters to send to the API endpoint
for the alert definition get escalation level integration operation typically these are written to a http.Request
*/
type AlertDefinitionGetEscalationLevelIntegrationParams struct {

	/*AlertDefinitionGUID
	  The Guid of the alert definition.

	*/
	AlertDefinitionGUID string
	/*EscalationLevelID
	  The escalation level id.

	*/
	EscalationLevelID int64
	/*IntegrationGUID
	  The Guid of the integration.

	*/
	IntegrationGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WithTimeout(timeout time.Duration) *AlertDefinitionGetEscalationLevelIntegrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WithContext(ctx context.Context) *AlertDefinitionGetEscalationLevelIntegrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WithHTTPClient(client *http.Client) *AlertDefinitionGetEscalationLevelIntegrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlertDefinitionGUID adds the alertDefinitionGUID to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WithAlertDefinitionGUID(alertDefinitionGUID string) *AlertDefinitionGetEscalationLevelIntegrationParams {
	o.SetAlertDefinitionGUID(alertDefinitionGUID)
	return o
}

// SetAlertDefinitionGUID adds the alertDefinitionGuid to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) SetAlertDefinitionGUID(alertDefinitionGUID string) {
	o.AlertDefinitionGUID = alertDefinitionGUID
}

// WithEscalationLevelID adds the escalationLevelID to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WithEscalationLevelID(escalationLevelID int64) *AlertDefinitionGetEscalationLevelIntegrationParams {
	o.SetEscalationLevelID(escalationLevelID)
	return o
}

// SetEscalationLevelID adds the escalationLevelId to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) SetEscalationLevelID(escalationLevelID int64) {
	o.EscalationLevelID = escalationLevelID
}

// WithIntegrationGUID adds the integrationGUID to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WithIntegrationGUID(integrationGUID string) *AlertDefinitionGetEscalationLevelIntegrationParams {
	o.SetIntegrationGUID(integrationGUID)
	return o
}

// SetIntegrationGUID adds the integrationGuid to the alert definition get escalation level integration params
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) SetIntegrationGUID(integrationGUID string) {
	o.IntegrationGUID = integrationGUID
}

// WriteToRequest writes these params to a swagger request
func (o *AlertDefinitionGetEscalationLevelIntegrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param alertDefinitionGuid
	if err := r.SetPathParam("alertDefinitionGuid", o.AlertDefinitionGUID); err != nil {
		return err
	}

	// path param escalationLevelId
	if err := r.SetPathParam("escalationLevelId", swag.FormatInt64(o.EscalationLevelID)); err != nil {
		return err
	}

	// path param integrationGuid
	if err := r.SetPathParam("integrationGuid", o.IntegrationGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
