// Code generated by go-swagger; DO NOT EDIT.

package alert_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// AlertDefinitionCreateAlertDefinitionReader is a Reader for the AlertDefinitionCreateAlertDefinition structure.
type AlertDefinitionCreateAlertDefinitionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AlertDefinitionCreateAlertDefinitionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAlertDefinitionCreateAlertDefinitionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAlertDefinitionCreateAlertDefinitionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAlertDefinitionCreateAlertDefinitionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAlertDefinitionCreateAlertDefinitionCreated creates a AlertDefinitionCreateAlertDefinitionCreated with default headers values
func NewAlertDefinitionCreateAlertDefinitionCreated() *AlertDefinitionCreateAlertDefinitionCreated {
	return &AlertDefinitionCreateAlertDefinitionCreated{}
}

/*AlertDefinitionCreateAlertDefinitionCreated handles this case with default header values.

The request completed successfully.
*/
type AlertDefinitionCreateAlertDefinitionCreated struct {
	Payload *models.AlertDefinition
}

func (o *AlertDefinitionCreateAlertDefinitionCreated) Error() string {
	return fmt.Sprintf("[POST /AlertDefinition][%d] alertDefinitionCreateAlertDefinitionCreated  %+v", 201, o.Payload)
}

func (o *AlertDefinitionCreateAlertDefinitionCreated) GetPayload() *models.AlertDefinition {
	return o.Payload
}

func (o *AlertDefinitionCreateAlertDefinitionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertDefinition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAlertDefinitionCreateAlertDefinitionBadRequest creates a AlertDefinitionCreateAlertDefinitionBadRequest with default headers values
func NewAlertDefinitionCreateAlertDefinitionBadRequest() *AlertDefinitionCreateAlertDefinitionBadRequest {
	return &AlertDefinitionCreateAlertDefinitionBadRequest{}
}

/*AlertDefinitionCreateAlertDefinitionBadRequest handles this case with default header values.

The request failed.
*/
type AlertDefinitionCreateAlertDefinitionBadRequest struct {
	Payload *models.MessageList
}

func (o *AlertDefinitionCreateAlertDefinitionBadRequest) Error() string {
	return fmt.Sprintf("[POST /AlertDefinition][%d] alertDefinitionCreateAlertDefinitionBadRequest  %+v", 400, o.Payload)
}

func (o *AlertDefinitionCreateAlertDefinitionBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *AlertDefinitionCreateAlertDefinitionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAlertDefinitionCreateAlertDefinitionForbidden creates a AlertDefinitionCreateAlertDefinitionForbidden with default headers values
func NewAlertDefinitionCreateAlertDefinitionForbidden() *AlertDefinitionCreateAlertDefinitionForbidden {
	return &AlertDefinitionCreateAlertDefinitionForbidden{}
}

/*AlertDefinitionCreateAlertDefinitionForbidden handles this case with default header values.

One or more validation errors occurred.
*/
type AlertDefinitionCreateAlertDefinitionForbidden struct {
	Payload *models.MessageList
}

func (o *AlertDefinitionCreateAlertDefinitionForbidden) Error() string {
	return fmt.Sprintf("[POST /AlertDefinition][%d] alertDefinitionCreateAlertDefinitionForbidden  %+v", 403, o.Payload)
}

func (o *AlertDefinitionCreateAlertDefinitionForbidden) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *AlertDefinitionCreateAlertDefinitionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
