// Code generated by go-swagger; DO NOT EDIT.

package alert_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams creates a new AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams object
// with the default values initialized.
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams() *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	var ()
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParamsWithTimeout creates a new AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParamsWithTimeout(timeout time.Duration) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	var ()
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams{

		timeout: timeout,
	}
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParamsWithContext creates a new AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams object
// with the default values initialized, and the ability to set a context for a request
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParamsWithContext(ctx context.Context) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	var ()
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams{

		Context: ctx,
	}
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParamsWithHTTPClient creates a new AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionParamsWithHTTPClient(client *http.Client) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	var ()
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams{
		HTTPClient: client,
	}
}

/*AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams contains all the parameters to send to the API endpoint
for the alert definition remove monitor group from alert definition operation typically these are written to a http.Request
*/
type AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams struct {

	/*AlertDefinitionGUID
	  The Guid of the alert definition to modify.

	*/
	AlertDefinitionGUID string
	/*MonitorGroupGUID
	  The Guid of the monitor group to remove.

	*/
	MonitorGroupGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) WithTimeout(timeout time.Duration) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) WithContext(ctx context.Context) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) WithHTTPClient(client *http.Client) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlertDefinitionGUID adds the alertDefinitionGUID to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) WithAlertDefinitionGUID(alertDefinitionGUID string) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	o.SetAlertDefinitionGUID(alertDefinitionGUID)
	return o
}

// SetAlertDefinitionGUID adds the alertDefinitionGuid to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) SetAlertDefinitionGUID(alertDefinitionGUID string) {
	o.AlertDefinitionGUID = alertDefinitionGUID
}

// WithMonitorGroupGUID adds the monitorGroupGUID to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) WithMonitorGroupGUID(monitorGroupGUID string) *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams {
	o.SetMonitorGroupGUID(monitorGroupGUID)
	return o
}

// SetMonitorGroupGUID adds the monitorGroupGuid to the alert definition remove monitor group from alert definition params
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) SetMonitorGroupGUID(monitorGroupGUID string) {
	o.MonitorGroupGUID = monitorGroupGUID
}

// WriteToRequest writes these params to a swagger request
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param alertDefinitionGuid
	if err := r.SetPathParam("alertDefinitionGuid", o.AlertDefinitionGUID); err != nil {
		return err
	}

	// path param monitorGroupGuid
	if err := r.SetPathParam("monitorGroupGuid", o.MonitorGroupGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
