// Code generated by go-swagger; DO NOT EDIT.

package alert_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// AlertDefinitionRemoveMonitorGroupFromAlertDefinitionReader is a Reader for the AlertDefinitionRemoveMonitorGroupFromAlertDefinition structure.
type AlertDefinitionRemoveMonitorGroupFromAlertDefinitionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent creates a AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent with default headers values
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent() *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent {
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent{}
}

/*AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent handles this case with default header values.

The request completed successfully. No content is returned.
*/
type AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent struct {
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent) Error() string {
	return fmt.Sprintf("[DELETE /AlertDefinition/{alertDefinitionGuid}/Members/MonitorGroup/{monitorGroupGuid}][%d] alertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent ", 204)
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest creates a AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest with default headers values
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest() *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest {
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest{}
}

/*AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest handles this case with default header values.

The request failed.
*/
type AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest struct {
	Payload *models.MessageList
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /AlertDefinition/{alertDefinitionGuid}/Members/MonitorGroup/{monitorGroupGuid}][%d] alertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest  %+v", 400, o.Payload)
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden creates a AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden with default headers values
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden() *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden {
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden{}
}

/*AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden handles this case with default header values.

One or more validation errors occurred.
*/
type AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden struct {
	Payload *models.MessageList
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden) Error() string {
	return fmt.Sprintf("[DELETE /AlertDefinition/{alertDefinitionGuid}/Members/MonitorGroup/{monitorGroupGuid}][%d] alertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden  %+v", 403, o.Payload)
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound creates a AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound with default headers values
func NewAlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound() *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound {
	return &AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound{}
}

/*AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound handles this case with default header values.

One or more of the specified entities could not be found.
*/
type AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound struct {
	Payload *models.MessageList
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /AlertDefinition/{alertDefinitionGuid}/Members/MonitorGroup/{monitorGroupGuid}][%d] alertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound  %+v", 404, o.Payload)
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *AlertDefinitionRemoveMonitorGroupFromAlertDefinitionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
