// Code generated by go-swagger; DO NOT EDIT.

package alert_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAlertDefinitionGetAllAlertDefinitionsParams creates a new AlertDefinitionGetAllAlertDefinitionsParams object
// with the default values initialized.
func NewAlertDefinitionGetAllAlertDefinitionsParams() *AlertDefinitionGetAllAlertDefinitionsParams {

	return &AlertDefinitionGetAllAlertDefinitionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAlertDefinitionGetAllAlertDefinitionsParamsWithTimeout creates a new AlertDefinitionGetAllAlertDefinitionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAlertDefinitionGetAllAlertDefinitionsParamsWithTimeout(timeout time.Duration) *AlertDefinitionGetAllAlertDefinitionsParams {

	return &AlertDefinitionGetAllAlertDefinitionsParams{

		timeout: timeout,
	}
}

// NewAlertDefinitionGetAllAlertDefinitionsParamsWithContext creates a new AlertDefinitionGetAllAlertDefinitionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAlertDefinitionGetAllAlertDefinitionsParamsWithContext(ctx context.Context) *AlertDefinitionGetAllAlertDefinitionsParams {

	return &AlertDefinitionGetAllAlertDefinitionsParams{

		Context: ctx,
	}
}

// NewAlertDefinitionGetAllAlertDefinitionsParamsWithHTTPClient creates a new AlertDefinitionGetAllAlertDefinitionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAlertDefinitionGetAllAlertDefinitionsParamsWithHTTPClient(client *http.Client) *AlertDefinitionGetAllAlertDefinitionsParams {

	return &AlertDefinitionGetAllAlertDefinitionsParams{
		HTTPClient: client,
	}
}

/*AlertDefinitionGetAllAlertDefinitionsParams contains all the parameters to send to the API endpoint
for the alert definition get all alert definitions operation typically these are written to a http.Request
*/
type AlertDefinitionGetAllAlertDefinitionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the alert definition get all alert definitions params
func (o *AlertDefinitionGetAllAlertDefinitionsParams) WithTimeout(timeout time.Duration) *AlertDefinitionGetAllAlertDefinitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the alert definition get all alert definitions params
func (o *AlertDefinitionGetAllAlertDefinitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the alert definition get all alert definitions params
func (o *AlertDefinitionGetAllAlertDefinitionsParams) WithContext(ctx context.Context) *AlertDefinitionGetAllAlertDefinitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the alert definition get all alert definitions params
func (o *AlertDefinitionGetAllAlertDefinitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the alert definition get all alert definitions params
func (o *AlertDefinitionGetAllAlertDefinitionsParams) WithHTTPClient(client *http.Client) *AlertDefinitionGetAllAlertDefinitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the alert definition get all alert definitions params
func (o *AlertDefinitionGetAllAlertDefinitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AlertDefinitionGetAllAlertDefinitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
