// Code generated by go-swagger; DO NOT EDIT.

package alert_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// NewAlertDefinitionPutAlertDefinitionParams creates a new AlertDefinitionPutAlertDefinitionParams object
// with the default values initialized.
func NewAlertDefinitionPutAlertDefinitionParams() *AlertDefinitionPutAlertDefinitionParams {
	var ()
	return &AlertDefinitionPutAlertDefinitionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAlertDefinitionPutAlertDefinitionParamsWithTimeout creates a new AlertDefinitionPutAlertDefinitionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAlertDefinitionPutAlertDefinitionParamsWithTimeout(timeout time.Duration) *AlertDefinitionPutAlertDefinitionParams {
	var ()
	return &AlertDefinitionPutAlertDefinitionParams{

		timeout: timeout,
	}
}

// NewAlertDefinitionPutAlertDefinitionParamsWithContext creates a new AlertDefinitionPutAlertDefinitionParams object
// with the default values initialized, and the ability to set a context for a request
func NewAlertDefinitionPutAlertDefinitionParamsWithContext(ctx context.Context) *AlertDefinitionPutAlertDefinitionParams {
	var ()
	return &AlertDefinitionPutAlertDefinitionParams{

		Context: ctx,
	}
}

// NewAlertDefinitionPutAlertDefinitionParamsWithHTTPClient creates a new AlertDefinitionPutAlertDefinitionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAlertDefinitionPutAlertDefinitionParamsWithHTTPClient(client *http.Client) *AlertDefinitionPutAlertDefinitionParams {
	var ()
	return &AlertDefinitionPutAlertDefinitionParams{
		HTTPClient: client,
	}
}

/*AlertDefinitionPutAlertDefinitionParams contains all the parameters to send to the API endpoint
for the alert definition put alert definition operation typically these are written to a http.Request
*/
type AlertDefinitionPutAlertDefinitionParams struct {

	/*AlertDefinition
	  The partial definition for the alert definition that should be updated.

	*/
	AlertDefinition *models.AlertDefinition
	/*AlertDefinitionGUID
	  The Guid of the alert definition that should be updated.

	*/
	AlertDefinitionGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) WithTimeout(timeout time.Duration) *AlertDefinitionPutAlertDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) WithContext(ctx context.Context) *AlertDefinitionPutAlertDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) WithHTTPClient(client *http.Client) *AlertDefinitionPutAlertDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlertDefinition adds the alertDefinition to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) WithAlertDefinition(alertDefinition *models.AlertDefinition) *AlertDefinitionPutAlertDefinitionParams {
	o.SetAlertDefinition(alertDefinition)
	return o
}

// SetAlertDefinition adds the alertDefinition to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) SetAlertDefinition(alertDefinition *models.AlertDefinition) {
	o.AlertDefinition = alertDefinition
}

// WithAlertDefinitionGUID adds the alertDefinitionGUID to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) WithAlertDefinitionGUID(alertDefinitionGUID string) *AlertDefinitionPutAlertDefinitionParams {
	o.SetAlertDefinitionGUID(alertDefinitionGUID)
	return o
}

// SetAlertDefinitionGUID adds the alertDefinitionGuid to the alert definition put alert definition params
func (o *AlertDefinitionPutAlertDefinitionParams) SetAlertDefinitionGUID(alertDefinitionGUID string) {
	o.AlertDefinitionGUID = alertDefinitionGUID
}

// WriteToRequest writes these params to a swagger request
func (o *AlertDefinitionPutAlertDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AlertDefinition != nil {
		if err := r.SetBodyParam(o.AlertDefinition); err != nil {
			return err
		}
	}

	// path param alertDefinitionGuid
	if err := r.SetPathParam("alertDefinitionGuid", o.AlertDefinitionGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
