// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// AccountGetAccountStatisticsReader is a Reader for the AccountGetAccountStatistics structure.
type AccountGetAccountStatisticsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AccountGetAccountStatisticsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAccountGetAccountStatisticsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAccountGetAccountStatisticsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAccountGetAccountStatisticsOK creates a AccountGetAccountStatisticsOK with default headers values
func NewAccountGetAccountStatisticsOK() *AccountGetAccountStatisticsOK {
	return &AccountGetAccountStatisticsOK{}
}

/*AccountGetAccountStatisticsOK handles this case with default header values.

Request completed successfully.
*/
type AccountGetAccountStatisticsOK struct {
	Payload *models.AccountStatistics
}

func (o *AccountGetAccountStatisticsOK) Error() string {
	return fmt.Sprintf("[GET /Account][%d] accountGetAccountStatisticsOK  %+v", 200, o.Payload)
}

func (o *AccountGetAccountStatisticsOK) GetPayload() *models.AccountStatistics {
	return o.Payload
}

func (o *AccountGetAccountStatisticsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountStatistics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAccountGetAccountStatisticsBadRequest creates a AccountGetAccountStatisticsBadRequest with default headers values
func NewAccountGetAccountStatisticsBadRequest() *AccountGetAccountStatisticsBadRequest {
	return &AccountGetAccountStatisticsBadRequest{}
}

/*AccountGetAccountStatisticsBadRequest handles this case with default header values.

The request failed.
*/
type AccountGetAccountStatisticsBadRequest struct {
	Payload *models.MessageList
}

func (o *AccountGetAccountStatisticsBadRequest) Error() string {
	return fmt.Sprintf("[GET /Account][%d] accountGetAccountStatisticsBadRequest  %+v", 400, o.Payload)
}

func (o *AccountGetAccountStatisticsBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *AccountGetAccountStatisticsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
