// Code generated by go-swagger; DO NOT EDIT.

package sla

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/damoun/uptrends/v4/models"
)

// NewSLAPutExclusionPeriodParams creates a new SLAPutExclusionPeriodParams object
// with the default values initialized.
func NewSLAPutExclusionPeriodParams() *SLAPutExclusionPeriodParams {
	var ()
	return &SLAPutExclusionPeriodParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSLAPutExclusionPeriodParamsWithTimeout creates a new SLAPutExclusionPeriodParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSLAPutExclusionPeriodParamsWithTimeout(timeout time.Duration) *SLAPutExclusionPeriodParams {
	var ()
	return &SLAPutExclusionPeriodParams{

		timeout: timeout,
	}
}

// NewSLAPutExclusionPeriodParamsWithContext creates a new SLAPutExclusionPeriodParams object
// with the default values initialized, and the ability to set a context for a request
func NewSLAPutExclusionPeriodParamsWithContext(ctx context.Context) *SLAPutExclusionPeriodParams {
	var ()
	return &SLAPutExclusionPeriodParams{

		Context: ctx,
	}
}

// NewSLAPutExclusionPeriodParamsWithHTTPClient creates a new SLAPutExclusionPeriodParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSLAPutExclusionPeriodParamsWithHTTPClient(client *http.Client) *SLAPutExclusionPeriodParams {
	var ()
	return &SLAPutExclusionPeriodParams{
		HTTPClient: client,
	}
}

/*SLAPutExclusionPeriodParams contains all the parameters to send to the API endpoint
for the Sla put exclusion period operation typically these are written to a http.Request
*/
type SLAPutExclusionPeriodParams struct {

	/*ExclusionPeriod
	  The complete definition of the exclusion period.

	*/
	ExclusionPeriod *models.ExclusionPeriod
	/*ExclusionPeriodID
	  The id of the exclusion period.

	*/
	ExclusionPeriodID int32
	/*SLAGUID
	  The Guid of the SLA definition.

	*/
	SLAGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) WithTimeout(timeout time.Duration) *SLAPutExclusionPeriodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) WithContext(ctx context.Context) *SLAPutExclusionPeriodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) WithHTTPClient(client *http.Client) *SLAPutExclusionPeriodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclusionPeriod adds the exclusionPeriod to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) WithExclusionPeriod(exclusionPeriod *models.ExclusionPeriod) *SLAPutExclusionPeriodParams {
	o.SetExclusionPeriod(exclusionPeriod)
	return o
}

// SetExclusionPeriod adds the exclusionPeriod to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) SetExclusionPeriod(exclusionPeriod *models.ExclusionPeriod) {
	o.ExclusionPeriod = exclusionPeriod
}

// WithExclusionPeriodID adds the exclusionPeriodID to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) WithExclusionPeriodID(exclusionPeriodID int32) *SLAPutExclusionPeriodParams {
	o.SetExclusionPeriodID(exclusionPeriodID)
	return o
}

// SetExclusionPeriodID adds the exclusionPeriodId to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) SetExclusionPeriodID(exclusionPeriodID int32) {
	o.ExclusionPeriodID = exclusionPeriodID
}

// WithSLAGUID adds the sLAGUID to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) WithSLAGUID(sLAGUID string) *SLAPutExclusionPeriodParams {
	o.SetSLAGUID(sLAGUID)
	return o
}

// SetSLAGUID adds the slaGuid to the Sla put exclusion period params
func (o *SLAPutExclusionPeriodParams) SetSLAGUID(sLAGUID string) {
	o.SLAGUID = sLAGUID
}

// WriteToRequest writes these params to a swagger request
func (o *SLAPutExclusionPeriodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExclusionPeriod != nil {
		if err := r.SetBodyParam(o.ExclusionPeriod); err != nil {
			return err
		}
	}

	// path param exclusionPeriodId
	if err := r.SetPathParam("exclusionPeriodId", swag.FormatInt32(o.ExclusionPeriodID)); err != nil {
		return err
	}

	// path param slaGuid
	if err := r.SetPathParam("slaGuid", o.SLAGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
