// Code generated by go-swagger; DO NOT EDIT.

package sla

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// SLAPutSLAReader is a Reader for the SLAPutSLA structure.
type SLAPutSLAReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SLAPutSLAReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSLAPutSLANoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSLAPutSLABadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSLAPutSLANotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSLAPutSLANoContent creates a SLAPutSLANoContent with default headers values
func NewSLAPutSLANoContent() *SLAPutSLANoContent {
	return &SLAPutSLANoContent{}
}

/*SLAPutSLANoContent handles this case with default header values.

The request was successful. No content is returned.
*/
type SLAPutSLANoContent struct {
}

func (o *SLAPutSLANoContent) Error() string {
	return fmt.Sprintf("[PUT /Sla/{slaGuid}][%d] slaPutSlaNoContent ", 204)
}

func (o *SLAPutSLANoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSLAPutSLABadRequest creates a SLAPutSLABadRequest with default headers values
func NewSLAPutSLABadRequest() *SLAPutSLABadRequest {
	return &SLAPutSLABadRequest{}
}

/*SLAPutSLABadRequest handles this case with default header values.

The request failed.
*/
type SLAPutSLABadRequest struct {
	Payload *models.MessageList
}

func (o *SLAPutSLABadRequest) Error() string {
	return fmt.Sprintf("[PUT /Sla/{slaGuid}][%d] slaPutSlaBadRequest  %+v", 400, o.Payload)
}

func (o *SLAPutSLABadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *SLAPutSLABadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSLAPutSLANotFound creates a SLAPutSLANotFound with default headers values
func NewSLAPutSLANotFound() *SLAPutSLANotFound {
	return &SLAPutSLANotFound{}
}

/*SLAPutSLANotFound handles this case with default header values.

The specified SLA does not exist.
*/
type SLAPutSLANotFound struct {
	Payload *models.MessageList
}

func (o *SLAPutSLANotFound) Error() string {
	return fmt.Sprintf("[PUT /Sla/{slaGuid}][%d] slaPutSlaNotFound  %+v", 404, o.Payload)
}

func (o *SLAPutSLANotFound) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *SLAPutSLANotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
