// Code generated by go-swagger; DO NOT EDIT.

package sla

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// SLACreateSLAReader is a Reader for the SLACreateSLA structure.
type SLACreateSLAReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SLACreateSLAReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSLACreateSLACreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSLACreateSLABadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSLACreateSLAForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSLACreateSLACreated creates a SLACreateSLACreated with default headers values
func NewSLACreateSLACreated() *SLACreateSLACreated {
	return &SLACreateSLACreated{}
}

/*SLACreateSLACreated handles this case with default header values.

The request completed successfully.
*/
type SLACreateSLACreated struct {
	Payload *models.SLA
}

func (o *SLACreateSLACreated) Error() string {
	return fmt.Sprintf("[POST /Sla][%d] slaCreateSlaCreated  %+v", 201, o.Payload)
}

func (o *SLACreateSLACreated) GetPayload() *models.SLA {
	return o.Payload
}

func (o *SLACreateSLACreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SLA)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSLACreateSLABadRequest creates a SLACreateSLABadRequest with default headers values
func NewSLACreateSLABadRequest() *SLACreateSLABadRequest {
	return &SLACreateSLABadRequest{}
}

/*SLACreateSLABadRequest handles this case with default header values.

The request failed.
*/
type SLACreateSLABadRequest struct {
	Payload *models.MessageList
}

func (o *SLACreateSLABadRequest) Error() string {
	return fmt.Sprintf("[POST /Sla][%d] slaCreateSlaBadRequest  %+v", 400, o.Payload)
}

func (o *SLACreateSLABadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *SLACreateSLABadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSLACreateSLAForbidden creates a SLACreateSLAForbidden with default headers values
func NewSLACreateSLAForbidden() *SLACreateSLAForbidden {
	return &SLACreateSLAForbidden{}
}

/*SLACreateSLAForbidden handles this case with default header values.

One or more validation errors occurred.
*/
type SLACreateSLAForbidden struct {
	Payload *models.MessageList
}

func (o *SLACreateSLAForbidden) Error() string {
	return fmt.Sprintf("[POST /Sla][%d] slaCreateSlaForbidden  %+v", 403, o.Payload)
}

func (o *SLACreateSLAForbidden) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *SLACreateSLAForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
