// Code generated by go-swagger; DO NOT EDIT.

package monitor_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/damoun/uptrends/v4/models"
)

// MonitorCheckGetMonitorGroupDataReader is a Reader for the MonitorCheckGetMonitorGroupData structure.
type MonitorCheckGetMonitorGroupDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MonitorCheckGetMonitorGroupDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMonitorCheckGetMonitorGroupDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMonitorCheckGetMonitorGroupDataBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMonitorCheckGetMonitorGroupDataOK creates a MonitorCheckGetMonitorGroupDataOK with default headers values
func NewMonitorCheckGetMonitorGroupDataOK() *MonitorCheckGetMonitorGroupDataOK {
	return &MonitorCheckGetMonitorGroupDataOK{}
}

/*MonitorCheckGetMonitorGroupDataOK handles this case with default header values.

Monitor checks for the specified monitor group.
*/
type MonitorCheckGetMonitorGroupDataOK struct {
	Payload *models.MonitorCheckResponse
}

func (o *MonitorCheckGetMonitorGroupDataOK) Error() string {
	return fmt.Sprintf("[GET /MonitorCheck/MonitorGroup/{monitorGroupGuid}][%d] monitorCheckGetMonitorGroupDataOK  %+v", 200, o.Payload)
}

func (o *MonitorCheckGetMonitorGroupDataOK) GetPayload() *models.MonitorCheckResponse {
	return o.Payload
}

func (o *MonitorCheckGetMonitorGroupDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MonitorCheckResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMonitorCheckGetMonitorGroupDataBadRequest creates a MonitorCheckGetMonitorGroupDataBadRequest with default headers values
func NewMonitorCheckGetMonitorGroupDataBadRequest() *MonitorCheckGetMonitorGroupDataBadRequest {
	return &MonitorCheckGetMonitorGroupDataBadRequest{}
}

/*MonitorCheckGetMonitorGroupDataBadRequest handles this case with default header values.

The request failed.
*/
type MonitorCheckGetMonitorGroupDataBadRequest struct {
	Payload *models.APIMessageInfo
}

func (o *MonitorCheckGetMonitorGroupDataBadRequest) Error() string {
	return fmt.Sprintf("[GET /MonitorCheck/MonitorGroup/{monitorGroupGuid}][%d] monitorCheckGetMonitorGroupDataBadRequest  %+v", 400, o.Payload)
}

func (o *MonitorCheckGetMonitorGroupDataBadRequest) GetPayload() *models.APIMessageInfo {
	return o.Payload
}

func (o *MonitorCheckGetMonitorGroupDataBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMessageInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
