// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewMonitorDeleteMaintenancePeriodFromMonitorParams creates a new MonitorDeleteMaintenancePeriodFromMonitorParams object
// with the default values initialized.
func NewMonitorDeleteMaintenancePeriodFromMonitorParams() *MonitorDeleteMaintenancePeriodFromMonitorParams {
	var ()
	return &MonitorDeleteMaintenancePeriodFromMonitorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMonitorDeleteMaintenancePeriodFromMonitorParamsWithTimeout creates a new MonitorDeleteMaintenancePeriodFromMonitorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMonitorDeleteMaintenancePeriodFromMonitorParamsWithTimeout(timeout time.Duration) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	var ()
	return &MonitorDeleteMaintenancePeriodFromMonitorParams{

		timeout: timeout,
	}
}

// NewMonitorDeleteMaintenancePeriodFromMonitorParamsWithContext creates a new MonitorDeleteMaintenancePeriodFromMonitorParams object
// with the default values initialized, and the ability to set a context for a request
func NewMonitorDeleteMaintenancePeriodFromMonitorParamsWithContext(ctx context.Context) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	var ()
	return &MonitorDeleteMaintenancePeriodFromMonitorParams{

		Context: ctx,
	}
}

// NewMonitorDeleteMaintenancePeriodFromMonitorParamsWithHTTPClient creates a new MonitorDeleteMaintenancePeriodFromMonitorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMonitorDeleteMaintenancePeriodFromMonitorParamsWithHTTPClient(client *http.Client) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	var ()
	return &MonitorDeleteMaintenancePeriodFromMonitorParams{
		HTTPClient: client,
	}
}

/*MonitorDeleteMaintenancePeriodFromMonitorParams contains all the parameters to send to the API endpoint
for the monitor delete maintenance period from monitor operation typically these are written to a http.Request
*/
type MonitorDeleteMaintenancePeriodFromMonitorParams struct {

	/*MaintenancePeriodID*/
	MaintenancePeriodID int32
	/*MonitorGUID*/
	MonitorGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) WithTimeout(timeout time.Duration) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) WithContext(ctx context.Context) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) WithHTTPClient(client *http.Client) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMaintenancePeriodID adds the maintenancePeriodID to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) WithMaintenancePeriodID(maintenancePeriodID int32) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	o.SetMaintenancePeriodID(maintenancePeriodID)
	return o
}

// SetMaintenancePeriodID adds the maintenancePeriodId to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) SetMaintenancePeriodID(maintenancePeriodID int32) {
	o.MaintenancePeriodID = maintenancePeriodID
}

// WithMonitorGUID adds the monitorGUID to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) WithMonitorGUID(monitorGUID string) *MonitorDeleteMaintenancePeriodFromMonitorParams {
	o.SetMonitorGUID(monitorGUID)
	return o
}

// SetMonitorGUID adds the monitorGuid to the monitor delete maintenance period from monitor params
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) SetMonitorGUID(monitorGUID string) {
	o.MonitorGUID = monitorGUID
}

// WriteToRequest writes these params to a swagger request
func (o *MonitorDeleteMaintenancePeriodFromMonitorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param maintenancePeriodId
	if err := r.SetPathParam("maintenancePeriodId", swag.FormatInt32(o.MaintenancePeriodID)); err != nil {
		return err
	}

	// path param monitorGuid
	if err := r.SetPathParam("monitorGuid", o.MonitorGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
