// Code generated by go-swagger; DO NOT EDIT.

package monitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMonitorGetMonitorsParams creates a new MonitorGetMonitorsParams object
// with the default values initialized.
func NewMonitorGetMonitorsParams() *MonitorGetMonitorsParams {
	var ()
	return &MonitorGetMonitorsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMonitorGetMonitorsParamsWithTimeout creates a new MonitorGetMonitorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMonitorGetMonitorsParamsWithTimeout(timeout time.Duration) *MonitorGetMonitorsParams {
	var ()
	return &MonitorGetMonitorsParams{

		timeout: timeout,
	}
}

// NewMonitorGetMonitorsParamsWithContext creates a new MonitorGetMonitorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewMonitorGetMonitorsParamsWithContext(ctx context.Context) *MonitorGetMonitorsParams {
	var ()
	return &MonitorGetMonitorsParams{

		Context: ctx,
	}
}

// NewMonitorGetMonitorsParamsWithHTTPClient creates a new MonitorGetMonitorsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMonitorGetMonitorsParamsWithHTTPClient(client *http.Client) *MonitorGetMonitorsParams {
	var ()
	return &MonitorGetMonitorsParams{
		HTTPClient: client,
	}
}

/*MonitorGetMonitorsParams contains all the parameters to send to the API endpoint
for the monitor get monitors operation typically these are written to a http.Request
*/
type MonitorGetMonitorsParams struct {

	/*Filter
	  Provide the option to only retrieve the requested fields. E.g. "Name,IsActive".

	*/
	Filter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the monitor get monitors params
func (o *MonitorGetMonitorsParams) WithTimeout(timeout time.Duration) *MonitorGetMonitorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the monitor get monitors params
func (o *MonitorGetMonitorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the monitor get monitors params
func (o *MonitorGetMonitorsParams) WithContext(ctx context.Context) *MonitorGetMonitorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the monitor get monitors params
func (o *MonitorGetMonitorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the monitor get monitors params
func (o *MonitorGetMonitorsParams) WithHTTPClient(client *http.Client) *MonitorGetMonitorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the monitor get monitors params
func (o *MonitorGetMonitorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the monitor get monitors params
func (o *MonitorGetMonitorsParams) WithFilter(filter *string) *MonitorGetMonitorsParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the monitor get monitors params
func (o *MonitorGetMonitorsParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WriteToRequest writes these params to a swagger request
func (o *MonitorGetMonitorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
