// Code generated by go-swagger; DO NOT EDIT.

package public_status_page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPublicStatusPageGetPublicStatusPageParams creates a new PublicStatusPageGetPublicStatusPageParams object
// with the default values initialized.
func NewPublicStatusPageGetPublicStatusPageParams() *PublicStatusPageGetPublicStatusPageParams {
	var ()
	return &PublicStatusPageGetPublicStatusPageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPublicStatusPageGetPublicStatusPageParamsWithTimeout creates a new PublicStatusPageGetPublicStatusPageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPublicStatusPageGetPublicStatusPageParamsWithTimeout(timeout time.Duration) *PublicStatusPageGetPublicStatusPageParams {
	var ()
	return &PublicStatusPageGetPublicStatusPageParams{

		timeout: timeout,
	}
}

// NewPublicStatusPageGetPublicStatusPageParamsWithContext creates a new PublicStatusPageGetPublicStatusPageParams object
// with the default values initialized, and the ability to set a context for a request
func NewPublicStatusPageGetPublicStatusPageParamsWithContext(ctx context.Context) *PublicStatusPageGetPublicStatusPageParams {
	var ()
	return &PublicStatusPageGetPublicStatusPageParams{

		Context: ctx,
	}
}

// NewPublicStatusPageGetPublicStatusPageParamsWithHTTPClient creates a new PublicStatusPageGetPublicStatusPageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPublicStatusPageGetPublicStatusPageParamsWithHTTPClient(client *http.Client) *PublicStatusPageGetPublicStatusPageParams {
	var ()
	return &PublicStatusPageGetPublicStatusPageParams{
		HTTPClient: client,
	}
}

/*PublicStatusPageGetPublicStatusPageParams contains all the parameters to send to the API endpoint
for the public status page get public status page operation typically these are written to a http.Request
*/
type PublicStatusPageGetPublicStatusPageParams struct {

	/*PublicStatusPageGUID
	  The Guid of the requested public status page.

	*/
	PublicStatusPageGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) WithTimeout(timeout time.Duration) *PublicStatusPageGetPublicStatusPageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) WithContext(ctx context.Context) *PublicStatusPageGetPublicStatusPageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) WithHTTPClient(client *http.Client) *PublicStatusPageGetPublicStatusPageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPublicStatusPageGUID adds the publicStatusPageGUID to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) WithPublicStatusPageGUID(publicStatusPageGUID string) *PublicStatusPageGetPublicStatusPageParams {
	o.SetPublicStatusPageGUID(publicStatusPageGUID)
	return o
}

// SetPublicStatusPageGUID adds the publicStatusPageGuid to the public status page get public status page params
func (o *PublicStatusPageGetPublicStatusPageParams) SetPublicStatusPageGUID(publicStatusPageGUID string) {
	o.PublicStatusPageGUID = publicStatusPageGUID
}

// WriteToRequest writes these params to a swagger request
func (o *PublicStatusPageGetPublicStatusPageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param publicStatusPageGuid
	if err := r.SetPathParam("publicStatusPageGuid", o.PublicStatusPageGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
