// Code generated by go-swagger; DO NOT EDIT.

package public_status_page

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// PublicStatusPageDeletePublicStatusPageReader is a Reader for the PublicStatusPageDeletePublicStatusPage structure.
type PublicStatusPageDeletePublicStatusPageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicStatusPageDeletePublicStatusPageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPublicStatusPageDeletePublicStatusPageNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPublicStatusPageDeletePublicStatusPageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPublicStatusPageDeletePublicStatusPageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPublicStatusPageDeletePublicStatusPageNoContent creates a PublicStatusPageDeletePublicStatusPageNoContent with default headers values
func NewPublicStatusPageDeletePublicStatusPageNoContent() *PublicStatusPageDeletePublicStatusPageNoContent {
	return &PublicStatusPageDeletePublicStatusPageNoContent{}
}

/*PublicStatusPageDeletePublicStatusPageNoContent handles this case with default header values.

The request was successful. No content is returned.
*/
type PublicStatusPageDeletePublicStatusPageNoContent struct {
}

func (o *PublicStatusPageDeletePublicStatusPageNoContent) Error() string {
	return fmt.Sprintf("[DELETE /PublicStatusPage/{publicStatusPageGuid}][%d] publicStatusPageDeletePublicStatusPageNoContent ", 204)
}

func (o *PublicStatusPageDeletePublicStatusPageNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPublicStatusPageDeletePublicStatusPageBadRequest creates a PublicStatusPageDeletePublicStatusPageBadRequest with default headers values
func NewPublicStatusPageDeletePublicStatusPageBadRequest() *PublicStatusPageDeletePublicStatusPageBadRequest {
	return &PublicStatusPageDeletePublicStatusPageBadRequest{}
}

/*PublicStatusPageDeletePublicStatusPageBadRequest handles this case with default header values.

The request failed.
*/
type PublicStatusPageDeletePublicStatusPageBadRequest struct {
	Payload *models.MessageList
}

func (o *PublicStatusPageDeletePublicStatusPageBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /PublicStatusPage/{publicStatusPageGuid}][%d] publicStatusPageDeletePublicStatusPageBadRequest  %+v", 400, o.Payload)
}

func (o *PublicStatusPageDeletePublicStatusPageBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *PublicStatusPageDeletePublicStatusPageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicStatusPageDeletePublicStatusPageNotFound creates a PublicStatusPageDeletePublicStatusPageNotFound with default headers values
func NewPublicStatusPageDeletePublicStatusPageNotFound() *PublicStatusPageDeletePublicStatusPageNotFound {
	return &PublicStatusPageDeletePublicStatusPageNotFound{}
}

/*PublicStatusPageDeletePublicStatusPageNotFound handles this case with default header values.

The specified public status page does not exist.
*/
type PublicStatusPageDeletePublicStatusPageNotFound struct {
	Payload *models.MessageList
}

func (o *PublicStatusPageDeletePublicStatusPageNotFound) Error() string {
	return fmt.Sprintf("[DELETE /PublicStatusPage/{publicStatusPageGuid}][%d] publicStatusPageDeletePublicStatusPageNotFound  %+v", 404, o.Payload)
}

func (o *PublicStatusPageDeletePublicStatusPageNotFound) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *PublicStatusPageDeletePublicStatusPageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
