// Code generated by go-swagger; DO NOT EDIT.

package operator_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// OperatorGroupGetAllOperatorGroupsReader is a Reader for the OperatorGroupGetAllOperatorGroups structure.
type OperatorGroupGetAllOperatorGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OperatorGroupGetAllOperatorGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOperatorGroupGetAllOperatorGroupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOperatorGroupGetAllOperatorGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOperatorGroupGetAllOperatorGroupsOK creates a OperatorGroupGetAllOperatorGroupsOK with default headers values
func NewOperatorGroupGetAllOperatorGroupsOK() *OperatorGroupGetAllOperatorGroupsOK {
	return &OperatorGroupGetAllOperatorGroupsOK{}
}

/*OperatorGroupGetAllOperatorGroupsOK handles this case with default header values.

The request completed successfully.
*/
type OperatorGroupGetAllOperatorGroupsOK struct {
	Payload []*models.OperatorGroup
}

func (o *OperatorGroupGetAllOperatorGroupsOK) Error() string {
	return fmt.Sprintf("[GET /OperatorGroup][%d] operatorGroupGetAllOperatorGroupsOK  %+v", 200, o.Payload)
}

func (o *OperatorGroupGetAllOperatorGroupsOK) GetPayload() []*models.OperatorGroup {
	return o.Payload
}

func (o *OperatorGroupGetAllOperatorGroupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOperatorGroupGetAllOperatorGroupsBadRequest creates a OperatorGroupGetAllOperatorGroupsBadRequest with default headers values
func NewOperatorGroupGetAllOperatorGroupsBadRequest() *OperatorGroupGetAllOperatorGroupsBadRequest {
	return &OperatorGroupGetAllOperatorGroupsBadRequest{}
}

/*OperatorGroupGetAllOperatorGroupsBadRequest handles this case with default header values.

The request failed.
*/
type OperatorGroupGetAllOperatorGroupsBadRequest struct {
	Payload *models.MessageList
}

func (o *OperatorGroupGetAllOperatorGroupsBadRequest) Error() string {
	return fmt.Sprintf("[GET /OperatorGroup][%d] operatorGroupGetAllOperatorGroupsBadRequest  %+v", 400, o.Payload)
}

func (o *OperatorGroupGetAllOperatorGroupsBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *OperatorGroupGetAllOperatorGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
