// Code generated by go-swagger; DO NOT EDIT.

package operator_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/damoun/uptrends/v4/models"
)

// OperatorGroupDeleteoperatorGroupReader is a Reader for the OperatorGroupDeleteoperatorGroup structure.
type OperatorGroupDeleteoperatorGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OperatorGroupDeleteoperatorGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewOperatorGroupDeleteoperatorGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOperatorGroupDeleteoperatorGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOperatorGroupDeleteoperatorGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOperatorGroupDeleteoperatorGroupNoContent creates a OperatorGroupDeleteoperatorGroupNoContent with default headers values
func NewOperatorGroupDeleteoperatorGroupNoContent() *OperatorGroupDeleteoperatorGroupNoContent {
	return &OperatorGroupDeleteoperatorGroupNoContent{}
}

/*OperatorGroupDeleteoperatorGroupNoContent handles this case with default header values.

Request completed successfully.
*/
type OperatorGroupDeleteoperatorGroupNoContent struct {
}

func (o *OperatorGroupDeleteoperatorGroupNoContent) Error() string {
	return fmt.Sprintf("[DELETE /OperatorGroup/{operatorGroupGuid}][%d] operatorGroupDeleteoperatorGroupNoContent ", 204)
}

func (o *OperatorGroupDeleteoperatorGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOperatorGroupDeleteoperatorGroupBadRequest creates a OperatorGroupDeleteoperatorGroupBadRequest with default headers values
func NewOperatorGroupDeleteoperatorGroupBadRequest() *OperatorGroupDeleteoperatorGroupBadRequest {
	return &OperatorGroupDeleteoperatorGroupBadRequest{}
}

/*OperatorGroupDeleteoperatorGroupBadRequest handles this case with default header values.

The request failed.
or
Deleting the Alloperators group is not allowed.
*/
type OperatorGroupDeleteoperatorGroupBadRequest struct {
	Payload *models.APIMessageInfo
}

func (o *OperatorGroupDeleteoperatorGroupBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /OperatorGroup/{operatorGroupGuid}][%d] operatorGroupDeleteoperatorGroupBadRequest  %+v", 400, o.Payload)
}

func (o *OperatorGroupDeleteoperatorGroupBadRequest) GetPayload() *models.APIMessageInfo {
	return o.Payload
}

func (o *OperatorGroupDeleteoperatorGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMessageInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOperatorGroupDeleteoperatorGroupNotFound creates a OperatorGroupDeleteoperatorGroupNotFound with default headers values
func NewOperatorGroupDeleteoperatorGroupNotFound() *OperatorGroupDeleteoperatorGroupNotFound {
	return &OperatorGroupDeleteoperatorGroupNotFound{}
}

/*OperatorGroupDeleteoperatorGroupNotFound handles this case with default header values.

The requested operator group was not found.
*/
type OperatorGroupDeleteoperatorGroupNotFound struct {
	Payload *models.APIMessageInfo
}

func (o *OperatorGroupDeleteoperatorGroupNotFound) Error() string {
	return fmt.Sprintf("[DELETE /OperatorGroup/{operatorGroupGuid}][%d] operatorGroupDeleteoperatorGroupNotFound  %+v", 404, o.Payload)
}

func (o *OperatorGroupDeleteoperatorGroupNotFound) GetPayload() *models.APIMessageInfo {
	return o.Payload
}

func (o *OperatorGroupDeleteoperatorGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIMessageInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
