// Code generated by go-swagger; DO NOT EDIT.

package operator_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// OperatorGroupRemoveOperatorFromOperatorGroupReader is a Reader for the OperatorGroupRemoveOperatorFromOperatorGroup structure.
type OperatorGroupRemoveOperatorFromOperatorGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OperatorGroupRemoveOperatorFromOperatorGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewOperatorGroupRemoveOperatorFromOperatorGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOperatorGroupRemoveOperatorFromOperatorGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOperatorGroupRemoveOperatorFromOperatorGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOperatorGroupRemoveOperatorFromOperatorGroupNoContent creates a OperatorGroupRemoveOperatorFromOperatorGroupNoContent with default headers values
func NewOperatorGroupRemoveOperatorFromOperatorGroupNoContent() *OperatorGroupRemoveOperatorFromOperatorGroupNoContent {
	return &OperatorGroupRemoveOperatorFromOperatorGroupNoContent{}
}

/*OperatorGroupRemoveOperatorFromOperatorGroupNoContent handles this case with default header values.

The request completed successfully. No content is returned.
*/
type OperatorGroupRemoveOperatorFromOperatorGroupNoContent struct {
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupNoContent) Error() string {
	return fmt.Sprintf("[DELETE /OperatorGroup/{operatorGroupGuid}/Member/{operatorGuid}][%d] operatorGroupRemoveOperatorFromOperatorGroupNoContent ", 204)
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOperatorGroupRemoveOperatorFromOperatorGroupBadRequest creates a OperatorGroupRemoveOperatorFromOperatorGroupBadRequest with default headers values
func NewOperatorGroupRemoveOperatorFromOperatorGroupBadRequest() *OperatorGroupRemoveOperatorFromOperatorGroupBadRequest {
	return &OperatorGroupRemoveOperatorFromOperatorGroupBadRequest{}
}

/*OperatorGroupRemoveOperatorFromOperatorGroupBadRequest handles this case with default header values.

The request failed.
or
A operator cannot be removed from the All operators group.
*/
type OperatorGroupRemoveOperatorFromOperatorGroupBadRequest struct {
	Payload *models.MessageList
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /OperatorGroup/{operatorGroupGuid}/Member/{operatorGuid}][%d] operatorGroupRemoveOperatorFromOperatorGroupBadRequest  %+v", 400, o.Payload)
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOperatorGroupRemoveOperatorFromOperatorGroupNotFound creates a OperatorGroupRemoveOperatorFromOperatorGroupNotFound with default headers values
func NewOperatorGroupRemoveOperatorFromOperatorGroupNotFound() *OperatorGroupRemoveOperatorFromOperatorGroupNotFound {
	return &OperatorGroupRemoveOperatorFromOperatorGroupNotFound{}
}

/*OperatorGroupRemoveOperatorFromOperatorGroupNotFound handles this case with default header values.

The requested operator group was not found.
*/
type OperatorGroupRemoveOperatorFromOperatorGroupNotFound struct {
	Payload *models.MessageList
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupNotFound) Error() string {
	return fmt.Sprintf("[DELETE /OperatorGroup/{operatorGroupGuid}/Member/{operatorGuid}][%d] operatorGroupRemoveOperatorFromOperatorGroupNotFound  %+v", 404, o.Payload)
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupNotFound) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *OperatorGroupRemoveOperatorFromOperatorGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
