// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// StatusGetMonitorGroupStatusReader is a Reader for the StatusGetMonitorGroupStatus structure.
type StatusGetMonitorGroupStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatusGetMonitorGroupStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStatusGetMonitorGroupStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStatusGetMonitorGroupStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewStatusGetMonitorGroupStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStatusGetMonitorGroupStatusOK creates a StatusGetMonitorGroupStatusOK with default headers values
func NewStatusGetMonitorGroupStatusOK() *StatusGetMonitorGroupStatusOK {
	return &StatusGetMonitorGroupStatusOK{}
}

/*StatusGetMonitorGroupStatusOK handles this case with default header values.

The request completed successfully.
*/
type StatusGetMonitorGroupStatusOK struct {
	Payload *models.MonitorStatusListResponse
}

func (o *StatusGetMonitorGroupStatusOK) Error() string {
	return fmt.Sprintf("[GET /Status/MonitorGroup/{monitorGroupGuid}][%d] statusGetMonitorGroupStatusOK  %+v", 200, o.Payload)
}

func (o *StatusGetMonitorGroupStatusOK) GetPayload() *models.MonitorStatusListResponse {
	return o.Payload
}

func (o *StatusGetMonitorGroupStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MonitorStatusListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStatusGetMonitorGroupStatusBadRequest creates a StatusGetMonitorGroupStatusBadRequest with default headers values
func NewStatusGetMonitorGroupStatusBadRequest() *StatusGetMonitorGroupStatusBadRequest {
	return &StatusGetMonitorGroupStatusBadRequest{}
}

/*StatusGetMonitorGroupStatusBadRequest handles this case with default header values.

The request failed.
*/
type StatusGetMonitorGroupStatusBadRequest struct {
	Payload *models.MessageList
}

func (o *StatusGetMonitorGroupStatusBadRequest) Error() string {
	return fmt.Sprintf("[GET /Status/MonitorGroup/{monitorGroupGuid}][%d] statusGetMonitorGroupStatusBadRequest  %+v", 400, o.Payload)
}

func (o *StatusGetMonitorGroupStatusBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *StatusGetMonitorGroupStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStatusGetMonitorGroupStatusNotFound creates a StatusGetMonitorGroupStatusNotFound with default headers values
func NewStatusGetMonitorGroupStatusNotFound() *StatusGetMonitorGroupStatusNotFound {
	return &StatusGetMonitorGroupStatusNotFound{}
}

/*StatusGetMonitorGroupStatusNotFound handles this case with default header values.

The monitor group could not be found.
*/
type StatusGetMonitorGroupStatusNotFound struct {
	Payload *models.MessageList
}

func (o *StatusGetMonitorGroupStatusNotFound) Error() string {
	return fmt.Sprintf("[GET /Status/MonitorGroup/{monitorGroupGuid}][%d] statusGetMonitorGroupStatusNotFound  %+v", 404, o.Payload)
}

func (o *StatusGetMonitorGroupStatusNotFound) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *StatusGetMonitorGroupStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
