// Code generated by go-swagger; DO NOT EDIT.

package operator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOperatorGetOperatorParams creates a new OperatorGetOperatorParams object
// with the default values initialized.
func NewOperatorGetOperatorParams() *OperatorGetOperatorParams {
	var ()
	return &OperatorGetOperatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOperatorGetOperatorParamsWithTimeout creates a new OperatorGetOperatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOperatorGetOperatorParamsWithTimeout(timeout time.Duration) *OperatorGetOperatorParams {
	var ()
	return &OperatorGetOperatorParams{

		timeout: timeout,
	}
}

// NewOperatorGetOperatorParamsWithContext creates a new OperatorGetOperatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewOperatorGetOperatorParamsWithContext(ctx context.Context) *OperatorGetOperatorParams {
	var ()
	return &OperatorGetOperatorParams{

		Context: ctx,
	}
}

// NewOperatorGetOperatorParamsWithHTTPClient creates a new OperatorGetOperatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOperatorGetOperatorParamsWithHTTPClient(client *http.Client) *OperatorGetOperatorParams {
	var ()
	return &OperatorGetOperatorParams{
		HTTPClient: client,
	}
}

/*OperatorGetOperatorParams contains all the parameters to send to the API endpoint
for the operator get operator operation typically these are written to a http.Request
*/
type OperatorGetOperatorParams struct {

	/*OperatorGUID
	  The Guid of the operator for which to retrieve the details

	*/
	OperatorGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the operator get operator params
func (o *OperatorGetOperatorParams) WithTimeout(timeout time.Duration) *OperatorGetOperatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the operator get operator params
func (o *OperatorGetOperatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the operator get operator params
func (o *OperatorGetOperatorParams) WithContext(ctx context.Context) *OperatorGetOperatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the operator get operator params
func (o *OperatorGetOperatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the operator get operator params
func (o *OperatorGetOperatorParams) WithHTTPClient(client *http.Client) *OperatorGetOperatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the operator get operator params
func (o *OperatorGetOperatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperatorGUID adds the operatorGUID to the operator get operator params
func (o *OperatorGetOperatorParams) WithOperatorGUID(operatorGUID string) *OperatorGetOperatorParams {
	o.SetOperatorGUID(operatorGUID)
	return o
}

// SetOperatorGUID adds the operatorGuid to the operator get operator params
func (o *OperatorGetOperatorParams) SetOperatorGUID(operatorGUID string) {
	o.OperatorGUID = operatorGUID
}

// WriteToRequest writes these params to a swagger request
func (o *OperatorGetOperatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param operatorGuid
	if err := r.SetPathParam("operatorGuid", o.OperatorGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
