// Code generated by go-swagger; DO NOT EDIT.

package operator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOperatorDeleteOperatorParams creates a new OperatorDeleteOperatorParams object
// with the default values initialized.
func NewOperatorDeleteOperatorParams() *OperatorDeleteOperatorParams {
	var ()
	return &OperatorDeleteOperatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOperatorDeleteOperatorParamsWithTimeout creates a new OperatorDeleteOperatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOperatorDeleteOperatorParamsWithTimeout(timeout time.Duration) *OperatorDeleteOperatorParams {
	var ()
	return &OperatorDeleteOperatorParams{

		timeout: timeout,
	}
}

// NewOperatorDeleteOperatorParamsWithContext creates a new OperatorDeleteOperatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewOperatorDeleteOperatorParamsWithContext(ctx context.Context) *OperatorDeleteOperatorParams {
	var ()
	return &OperatorDeleteOperatorParams{

		Context: ctx,
	}
}

// NewOperatorDeleteOperatorParamsWithHTTPClient creates a new OperatorDeleteOperatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOperatorDeleteOperatorParamsWithHTTPClient(client *http.Client) *OperatorDeleteOperatorParams {
	var ()
	return &OperatorDeleteOperatorParams{
		HTTPClient: client,
	}
}

/*OperatorDeleteOperatorParams contains all the parameters to send to the API endpoint
for the operator delete operator operation typically these are written to a http.Request
*/
type OperatorDeleteOperatorParams struct {

	/*OperatorGUID
	  The Guid of the operator to delete

	*/
	OperatorGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the operator delete operator params
func (o *OperatorDeleteOperatorParams) WithTimeout(timeout time.Duration) *OperatorDeleteOperatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the operator delete operator params
func (o *OperatorDeleteOperatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the operator delete operator params
func (o *OperatorDeleteOperatorParams) WithContext(ctx context.Context) *OperatorDeleteOperatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the operator delete operator params
func (o *OperatorDeleteOperatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the operator delete operator params
func (o *OperatorDeleteOperatorParams) WithHTTPClient(client *http.Client) *OperatorDeleteOperatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the operator delete operator params
func (o *OperatorDeleteOperatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperatorGUID adds the operatorGUID to the operator delete operator params
func (o *OperatorDeleteOperatorParams) WithOperatorGUID(operatorGUID string) *OperatorDeleteOperatorParams {
	o.SetOperatorGUID(operatorGUID)
	return o
}

// SetOperatorGUID adds the operatorGuid to the operator delete operator params
func (o *OperatorDeleteOperatorParams) SetOperatorGUID(operatorGUID string) {
	o.OperatorGUID = operatorGUID
}

// WriteToRequest writes these params to a swagger request
func (o *OperatorDeleteOperatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param operatorGuid
	if err := r.SetPathParam("operatorGuid", o.OperatorGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
