// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AlertDefinitionMonitor alert definition monitor
//
// swagger:model AlertDefinitionMonitor
type AlertDefinitionMonitor struct {

	// alert definition
	// Required: true
	AlertDefinition *string `json:"AlertDefinition"`

	// monitor
	// Required: true
	Monitor *string `json:"Monitor"`
}

// Validate validates this alert definition monitor
func (m *AlertDefinitionMonitor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlertDefinition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMonitor(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AlertDefinitionMonitor) validateAlertDefinition(formats strfmt.Registry) error {

	if err := validate.Required("AlertDefinition", "body", m.AlertDefinition); err != nil {
		return err
	}

	return nil
}

func (m *AlertDefinitionMonitor) validateMonitor(formats strfmt.Registry) error {

	if err := validate.Required("Monitor", "body", m.Monitor); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AlertDefinitionMonitor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertDefinitionMonitor) UnmarshalBinary(b []byte) error {
	var res AlertDefinitionMonitor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
