// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// APIAssertionSourceType Api assertion source type
//
// swagger:model ApiAssertionSourceType
type APIAssertionSourceType string

const (

	// APIAssertionSourceTypeNone captures enum value "None"
	APIAssertionSourceTypeNone APIAssertionSourceType = "None"

	// APIAssertionSourceTypeConstant captures enum value "Constant"
	APIAssertionSourceTypeConstant APIAssertionSourceType = "Constant"

	// APIAssertionSourceTypeVariable captures enum value "Variable"
	APIAssertionSourceTypeVariable APIAssertionSourceType = "Variable"

	// APIAssertionSourceTypeResponseStatusCode captures enum value "ResponseStatusCode"
	APIAssertionSourceTypeResponseStatusCode APIAssertionSourceType = "ResponseStatusCode"

	// APIAssertionSourceTypeResponseStatusDescription captures enum value "ResponseStatusDescription"
	APIAssertionSourceTypeResponseStatusDescription APIAssertionSourceType = "ResponseStatusDescription"

	// APIAssertionSourceTypeResponseBodyJSON captures enum value "ResponseBodyJson"
	APIAssertionSourceTypeResponseBodyJSON APIAssertionSourceType = "ResponseBodyJson"

	// APIAssertionSourceTypeResponseCompleted captures enum value "ResponseCompleted"
	APIAssertionSourceTypeResponseCompleted APIAssertionSourceType = "ResponseCompleted"

	// APIAssertionSourceTypeResponseBodyText captures enum value "ResponseBodyText"
	APIAssertionSourceTypeResponseBodyText APIAssertionSourceType = "ResponseBodyText"

	// APIAssertionSourceTypeFail captures enum value "Fail"
	APIAssertionSourceTypeFail APIAssertionSourceType = "Fail"

	// APIAssertionSourceTypeContentLengthCalculated captures enum value "ContentLengthCalculated"
	APIAssertionSourceTypeContentLengthCalculated APIAssertionSourceType = "ContentLengthCalculated"

	// APIAssertionSourceTypeDuration captures enum value "Duration"
	APIAssertionSourceTypeDuration APIAssertionSourceType = "Duration"

	// APIAssertionSourceTypeSum captures enum value "Sum"
	APIAssertionSourceTypeSum APIAssertionSourceType = "Sum"

	// APIAssertionSourceTypeConcatenation captures enum value "Concatenation"
	APIAssertionSourceTypeConcatenation APIAssertionSourceType = "Concatenation"

	// APIAssertionSourceTypeToBase64 captures enum value "ToBase64"
	APIAssertionSourceTypeToBase64 APIAssertionSourceType = "ToBase64"

	// APIAssertionSourceTypeToSHA1Hex captures enum value "ToSHA1Hex"
	APIAssertionSourceTypeToSHA1Hex APIAssertionSourceType = "ToSHA1Hex"

	// APIAssertionSourceTypeToMD5Hex captures enum value "ToMD5Hex"
	APIAssertionSourceTypeToMD5Hex APIAssertionSourceType = "ToMD5Hex"

	// APIAssertionSourceTypeResponseBodyXML captures enum value "ResponseBodyXml"
	APIAssertionSourceTypeResponseBodyXML APIAssertionSourceType = "ResponseBodyXml"

	// APIAssertionSourceTypeResponseHeader captures enum value "ResponseHeader"
	APIAssertionSourceTypeResponseHeader APIAssertionSourceType = "ResponseHeader"

	// APIAssertionSourceTypeCookie captures enum value "Cookie"
	APIAssertionSourceTypeCookie APIAssertionSourceType = "Cookie"

	// APIAssertionSourceTypeVariablesResolved captures enum value "VariablesResolved"
	APIAssertionSourceTypeVariablesResolved APIAssertionSourceType = "VariablesResolved"

	// APIAssertionSourceTypeCumulativeDuration captures enum value "CumulativeDuration"
	APIAssertionSourceTypeCumulativeDuration APIAssertionSourceType = "CumulativeDuration"

	// APIAssertionSourceTypeResponseHasException captures enum value "ResponseHasException"
	APIAssertionSourceTypeResponseHasException APIAssertionSourceType = "ResponseHasException"
)

// for schema
var apiAssertionSourceTypeEnum []interface{}

func init() {
	var res []APIAssertionSourceType
	if err := json.Unmarshal([]byte(`["None","Constant","Variable","ResponseStatusCode","ResponseStatusDescription","ResponseBodyJson","ResponseCompleted","ResponseBodyText","Fail","ContentLengthCalculated","Duration","Sum","Concatenation","ToBase64","ToSHA1Hex","ToMD5Hex","ResponseBodyXml","ResponseHeader","Cookie","VariablesResolved","CumulativeDuration","ResponseHasException"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiAssertionSourceTypeEnum = append(apiAssertionSourceTypeEnum, v)
	}
}

func (m APIAssertionSourceType) validateAPIAssertionSourceTypeEnum(path, location string, value APIAssertionSourceType) error {
	if err := validate.EnumCase(path, location, value, apiAssertionSourceTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this Api assertion source type
func (m APIAssertionSourceType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAPIAssertionSourceTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
