// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// APIStepType Api step type
// swagger:model ApiStepType
type APIStepType string

const (

	// APIStepTypeHTTPRequest captures enum value "HttpRequest"
	APIStepTypeHTTPRequest APIStepType = "HttpRequest"

	// APIStepTypeDelay captures enum value "Delay"
	APIStepTypeDelay APIStepType = "Delay"
)

// for schema
var apiStepTypeEnum []interface{}

func init() {
	var res []APIStepType
	if err := json.Unmarshal([]byte(`["HttpRequest","Delay"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiStepTypeEnum = append(apiStepTypeEnum, v)
	}
}

func (m APIStepType) validateAPIStepTypeEnum(path, location string, value APIStepType) error {
	if err := validate.Enum(path, location, value, apiStepTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this Api step type
func (m APIStepType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAPIStepTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
