// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// MaintenanceTypes maintenance types
//
// swagger:model MaintenanceTypes
type MaintenanceTypes string

const (

	// MaintenanceTypesDisableMonitoring captures enum value "DisableMonitoring"
	MaintenanceTypesDisableMonitoring MaintenanceTypes = "DisableMonitoring"

	// MaintenanceTypesDisableNotifications captures enum value "DisableNotifications"
	MaintenanceTypesDisableNotifications MaintenanceTypes = "DisableNotifications"
)

// for schema
var maintenanceTypesEnum []interface{}

func init() {
	var res []MaintenanceTypes
	if err := json.Unmarshal([]byte(`["DisableMonitoring","DisableNotifications"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		maintenanceTypesEnum = append(maintenanceTypesEnum, v)
	}
}

func (m MaintenanceTypes) validateMaintenanceTypesEnum(path, location string, value MaintenanceTypes) error {
	if err := validate.EnumCase(path, location, value, maintenanceTypesEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this maintenance types
func (m MaintenanceTypes) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMaintenanceTypesEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
