// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OperatorGroupMember operator group member
// swagger:model OperatorGroupMember
type OperatorGroupMember struct {

	// operator Guid
	// Required: true
	OperatorGUID *string `json:"OperatorGuid"`
}

// Validate validates this operator group member
func (m *OperatorGroupMember) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOperatorGUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperatorGroupMember) validateOperatorGUID(formats strfmt.Registry) error {

	if err := validate.Required("OperatorGuid", "body", m.OperatorGUID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OperatorGroupMember) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperatorGroupMember) UnmarshalBinary(b []byte) error {
	var res OperatorGroupMember
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
