// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegistrationResponse registration response
//
// swagger:model RegistrationResponse
type RegistrationResponse struct {

	// The Uptrends Account Id for which the new API account was created
	AccountID string `json:"AccountId,omitempty"`

	// The Uptrends Operator on behalf of whom the new API account was created
	OperatorName string `json:"OperatorName,omitempty"`

	// The password of the new API account
	Password string `json:"Password,omitempty"`

	// The user name of the new API account
	UserName string `json:"UserName,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// status
	// Required: true
	Status RegisterStatus `json:"status"`
}

// Validate validates this registration response
func (m *RegistrationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegistrationResponse) validateStatus(formats strfmt.Registry) error {

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("status")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RegistrationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistrationResponse) UnmarshalBinary(b []byte) error {
	var res RegistrationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
