// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourceObject14 resource object14
// swagger:model ResourceObject14
type ResourceObject14 struct {
	ResourceObject8

	// attributes
	Attributes *HTTPEngineAttributes `json:"Attributes,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ResourceObject14) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ResourceObject8
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ResourceObject8 = aO0

	// now for regular properties
	var propsResourceObject14 struct {
		Attributes *HTTPEngineAttributes `json:"Attributes,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsResourceObject14); err != nil {
		return err
	}
	m.Attributes = propsResourceObject14.Attributes

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ResourceObject14) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ResourceObject8)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsResourceObject14 struct {
		Attributes *HTTPEngineAttributes `json:"Attributes,omitempty"`
	}
	propsResourceObject14.Attributes = m.Attributes

	jsonDataPropsResourceObject14, errResourceObject14 := swag.WriteJSON(propsResourceObject14)
	if errResourceObject14 != nil {
		return nil, errResourceObject14
	}
	_parts = append(_parts, jsonDataPropsResourceObject14)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this resource object14
func (m *ResourceObject14) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResourceObject8
	if err := m.ResourceObject8.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAttributes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceObject14) validateAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.Attributes) { // not required
		return nil
	}

	if m.Attributes != nil {
		if err := m.Attributes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Attributes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourceObject14) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceObject14) UnmarshalBinary(b []byte) error {
	var res ResourceObject14
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
