// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes response base of list of resource object of int16 and checkpoint attributes
// swagger:model ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes
type ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes struct {

	// data
	Data []*ResourceObject2 `json:"Data"`

	// links
	Links *LinksData `json:"Links,omitempty"`

	// meta
	Meta *MetaData `json:"Meta,omitempty"`

	// relationships
	Relationships []*RelationObject `json:"Relationships"`
}

// Validate validates this response base of list of resource object of int16 and checkpoint attributes
func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelationships(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {
		if swag.IsZero(m.Data[i]) { // not required
			continue
		}

		if m.Data[i] != nil {
			if err := m.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Links")
			}
			return err
		}
	}

	return nil
}

func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(m.Meta) { // not required
		return nil
	}

	if m.Meta != nil {
		if err := m.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Meta")
			}
			return err
		}
	}

	return nil
}

func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) validateRelationships(formats strfmt.Registry) error {

	if swag.IsZero(m.Relationships) { // not required
		return nil
	}

	for i := 0; i < len(m.Relationships); i++ {
		if swag.IsZero(m.Relationships[i]) { // not required
			continue
		}

		if m.Relationships[i] != nil {
			if err := m.Relationships[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Relationships" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes) UnmarshalBinary(b []byte) error {
	var res ResponseBaseOfListOfResourceObjectOfInt16AndCheckpointAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
