// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SLA Sla
//
// swagger:model Sla
type SLA struct {

	// The description name of this sla.
	Description string `json:"Description,omitempty"`

	// Hash corresponding with this sla.
	Hash string `json:"Hash,omitempty"`

	// load time error threshold
	LoadTimeErrorThreshold float64 `json:"LoadTimeErrorThreshold,omitempty"`

	// operator reponse time threshold
	OperatorReponseTimeThreshold int32 `json:"OperatorReponseTimeThreshold,omitempty"`

	// The unique key of this sla.
	SLAGUID string `json:"SlaGuid,omitempty"`

	// uptime error threshold
	UptimeErrorThreshold float64 `json:"UptimeErrorThreshold,omitempty"`

	// uptime warning threshold
	UptimeWarningThreshold float64 `json:"UptimeWarningThreshold,omitempty"`
}

// Validate validates this Sla
func (m *SLA) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SLA) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SLA) UnmarshalBinary(b []byte) error {
	var res SLA
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
