// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// TLSVersion Tls version
//
// swagger:model TlsVersion
type TLSVersion string

const (

	// TLSVersionTls12 captures enum value "Tls12"
	TLSVersionTls12 TLSVersion = "Tls12"

	// TLSVersionTls11 captures enum value "Tls11"
	TLSVersionTls11 TLSVersion = "Tls11"

	// TLSVersionTls10 captures enum value "Tls10"
	TLSVersionTls10 TLSVersion = "Tls10"

	// TLSVersionTls12Tls11 captures enum value "Tls12_Tls11"
	TLSVersionTls12Tls11 TLSVersion = "Tls12_Tls11"

	// TLSVersionTls11Tls10 captures enum value "Tls11_Tls10"
	TLSVersionTls11Tls10 TLSVersion = "Tls11_Tls10"

	// TLSVersionTls12Tls11Tls10 captures enum value "Tls12_Tls11_Tls10"
	TLSVersionTls12Tls11Tls10 TLSVersion = "Tls12_Tls11_Tls10"

	// TLSVersionTls12Tls11Tls10WithFallback captures enum value "Tls12_Tls11_Tls10_WithFallback"
	TLSVersionTls12Tls11Tls10WithFallback TLSVersion = "Tls12_Tls11_Tls10_WithFallback"
)

// for schema
var tlsVersionEnum []interface{}

func init() {
	var res []TLSVersion
	if err := json.Unmarshal([]byte(`["Tls12","Tls11","Tls10","Tls12_Tls11","Tls11_Tls10","Tls12_Tls11_Tls10","Tls12_Tls11_Tls10_WithFallback"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tlsVersionEnum = append(tlsVersionEnum, v)
	}
}

func (m TLSVersion) validateTLSVersionEnum(path, location string, value TLSVersion) error {
	if err := validate.EnumCase(path, location, value, tlsVersionEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this Tls version
func (m TLSVersion) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTLSVersionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
