// Code generated by go-swagger; DO NOT EDIT.

package checkpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckpointServerGetAllServerIPV4AddressesParams creates a new CheckpointServerGetAllServerIPV4AddressesParams object
// with the default values initialized.
func NewCheckpointServerGetAllServerIPV4AddressesParams() *CheckpointServerGetAllServerIPV4AddressesParams {

	return &CheckpointServerGetAllServerIPV4AddressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckpointServerGetAllServerIPV4AddressesParamsWithTimeout creates a new CheckpointServerGetAllServerIPV4AddressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckpointServerGetAllServerIPV4AddressesParamsWithTimeout(timeout time.Duration) *CheckpointServerGetAllServerIPV4AddressesParams {

	return &CheckpointServerGetAllServerIPV4AddressesParams{

		timeout: timeout,
	}
}

// NewCheckpointServerGetAllServerIPV4AddressesParamsWithContext creates a new CheckpointServerGetAllServerIPV4AddressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckpointServerGetAllServerIPV4AddressesParamsWithContext(ctx context.Context) *CheckpointServerGetAllServerIPV4AddressesParams {

	return &CheckpointServerGetAllServerIPV4AddressesParams{

		Context: ctx,
	}
}

// NewCheckpointServerGetAllServerIPV4AddressesParamsWithHTTPClient creates a new CheckpointServerGetAllServerIPV4AddressesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckpointServerGetAllServerIPV4AddressesParamsWithHTTPClient(client *http.Client) *CheckpointServerGetAllServerIPV4AddressesParams {

	return &CheckpointServerGetAllServerIPV4AddressesParams{
		HTTPClient: client,
	}
}

/*CheckpointServerGetAllServerIPV4AddressesParams contains all the parameters to send to the API endpoint
for the checkpoint server get all server Ipv4 addresses operation typically these are written to a http.Request
*/
type CheckpointServerGetAllServerIPV4AddressesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the checkpoint server get all server Ipv4 addresses params
func (o *CheckpointServerGetAllServerIPV4AddressesParams) WithTimeout(timeout time.Duration) *CheckpointServerGetAllServerIPV4AddressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the checkpoint server get all server Ipv4 addresses params
func (o *CheckpointServerGetAllServerIPV4AddressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the checkpoint server get all server Ipv4 addresses params
func (o *CheckpointServerGetAllServerIPV4AddressesParams) WithContext(ctx context.Context) *CheckpointServerGetAllServerIPV4AddressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the checkpoint server get all server Ipv4 addresses params
func (o *CheckpointServerGetAllServerIPV4AddressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the checkpoint server get all server Ipv4 addresses params
func (o *CheckpointServerGetAllServerIPV4AddressesParams) WithHTTPClient(client *http.Client) *CheckpointServerGetAllServerIPV4AddressesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the checkpoint server get all server Ipv4 addresses params
func (o *CheckpointServerGetAllServerIPV4AddressesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CheckpointServerGetAllServerIPV4AddressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
