// Code generated by go-swagger; DO NOT EDIT.

package monitor_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMonitorGroupGetAllMonitorGroupsParams creates a new MonitorGroupGetAllMonitorGroupsParams object
// with the default values initialized.
func NewMonitorGroupGetAllMonitorGroupsParams() *MonitorGroupGetAllMonitorGroupsParams {

	return &MonitorGroupGetAllMonitorGroupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMonitorGroupGetAllMonitorGroupsParamsWithTimeout creates a new MonitorGroupGetAllMonitorGroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMonitorGroupGetAllMonitorGroupsParamsWithTimeout(timeout time.Duration) *MonitorGroupGetAllMonitorGroupsParams {

	return &MonitorGroupGetAllMonitorGroupsParams{

		timeout: timeout,
	}
}

// NewMonitorGroupGetAllMonitorGroupsParamsWithContext creates a new MonitorGroupGetAllMonitorGroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewMonitorGroupGetAllMonitorGroupsParamsWithContext(ctx context.Context) *MonitorGroupGetAllMonitorGroupsParams {

	return &MonitorGroupGetAllMonitorGroupsParams{

		Context: ctx,
	}
}

// NewMonitorGroupGetAllMonitorGroupsParamsWithHTTPClient creates a new MonitorGroupGetAllMonitorGroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMonitorGroupGetAllMonitorGroupsParamsWithHTTPClient(client *http.Client) *MonitorGroupGetAllMonitorGroupsParams {

	return &MonitorGroupGetAllMonitorGroupsParams{
		HTTPClient: client,
	}
}

/*MonitorGroupGetAllMonitorGroupsParams contains all the parameters to send to the API endpoint
for the monitor group get all monitor groups operation typically these are written to a http.Request
*/
type MonitorGroupGetAllMonitorGroupsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the monitor group get all monitor groups params
func (o *MonitorGroupGetAllMonitorGroupsParams) WithTimeout(timeout time.Duration) *MonitorGroupGetAllMonitorGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the monitor group get all monitor groups params
func (o *MonitorGroupGetAllMonitorGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the monitor group get all monitor groups params
func (o *MonitorGroupGetAllMonitorGroupsParams) WithContext(ctx context.Context) *MonitorGroupGetAllMonitorGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the monitor group get all monitor groups params
func (o *MonitorGroupGetAllMonitorGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the monitor group get all monitor groups params
func (o *MonitorGroupGetAllMonitorGroupsParams) WithHTTPClient(client *http.Client) *MonitorGroupGetAllMonitorGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the monitor group get all monitor groups params
func (o *MonitorGroupGetAllMonitorGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MonitorGroupGetAllMonitorGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
