// Code generated by go-swagger; DO NOT EDIT.

package operator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/damoun/uptrends/models"
)

// NewOperatorCreateOperatorParams creates a new OperatorCreateOperatorParams object
// with the default values initialized.
func NewOperatorCreateOperatorParams() *OperatorCreateOperatorParams {
	var ()
	return &OperatorCreateOperatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOperatorCreateOperatorParamsWithTimeout creates a new OperatorCreateOperatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOperatorCreateOperatorParamsWithTimeout(timeout time.Duration) *OperatorCreateOperatorParams {
	var ()
	return &OperatorCreateOperatorParams{

		timeout: timeout,
	}
}

// NewOperatorCreateOperatorParamsWithContext creates a new OperatorCreateOperatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewOperatorCreateOperatorParamsWithContext(ctx context.Context) *OperatorCreateOperatorParams {
	var ()
	return &OperatorCreateOperatorParams{

		Context: ctx,
	}
}

// NewOperatorCreateOperatorParamsWithHTTPClient creates a new OperatorCreateOperatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOperatorCreateOperatorParamsWithHTTPClient(client *http.Client) *OperatorCreateOperatorParams {
	var ()
	return &OperatorCreateOperatorParams{
		HTTPClient: client,
	}
}

/*OperatorCreateOperatorParams contains all the parameters to send to the API endpoint
for the operator create operator operation typically these are written to a http.Request
*/
type OperatorCreateOperatorParams struct {

	/*UptrendsOperator
	  The details of the operator to create

	*/
	UptrendsOperator *models.Operator

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the operator create operator params
func (o *OperatorCreateOperatorParams) WithTimeout(timeout time.Duration) *OperatorCreateOperatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the operator create operator params
func (o *OperatorCreateOperatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the operator create operator params
func (o *OperatorCreateOperatorParams) WithContext(ctx context.Context) *OperatorCreateOperatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the operator create operator params
func (o *OperatorCreateOperatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the operator create operator params
func (o *OperatorCreateOperatorParams) WithHTTPClient(client *http.Client) *OperatorCreateOperatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the operator create operator params
func (o *OperatorCreateOperatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUptrendsOperator adds the uptrendsOperator to the operator create operator params
func (o *OperatorCreateOperatorParams) WithUptrendsOperator(uptrendsOperator *models.Operator) *OperatorCreateOperatorParams {
	o.SetUptrendsOperator(uptrendsOperator)
	return o
}

// SetUptrendsOperator adds the uptrendsOperator to the operator create operator params
func (o *OperatorCreateOperatorParams) SetUptrendsOperator(uptrendsOperator *models.Operator) {
	o.UptrendsOperator = uptrendsOperator
}

// WriteToRequest writes these params to a swagger request
func (o *OperatorCreateOperatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.UptrendsOperator != nil {
		if err := r.SetBodyParam(o.UptrendsOperator); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
