// Code generated by go-swagger; DO NOT EDIT.

package operator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOperatorGetOperatorGroupsForOperatorParams creates a new OperatorGetOperatorGroupsForOperatorParams object
// with the default values initialized.
func NewOperatorGetOperatorGroupsForOperatorParams() *OperatorGetOperatorGroupsForOperatorParams {
	var ()
	return &OperatorGetOperatorGroupsForOperatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOperatorGetOperatorGroupsForOperatorParamsWithTimeout creates a new OperatorGetOperatorGroupsForOperatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOperatorGetOperatorGroupsForOperatorParamsWithTimeout(timeout time.Duration) *OperatorGetOperatorGroupsForOperatorParams {
	var ()
	return &OperatorGetOperatorGroupsForOperatorParams{

		timeout: timeout,
	}
}

// NewOperatorGetOperatorGroupsForOperatorParamsWithContext creates a new OperatorGetOperatorGroupsForOperatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewOperatorGetOperatorGroupsForOperatorParamsWithContext(ctx context.Context) *OperatorGetOperatorGroupsForOperatorParams {
	var ()
	return &OperatorGetOperatorGroupsForOperatorParams{

		Context: ctx,
	}
}

// NewOperatorGetOperatorGroupsForOperatorParamsWithHTTPClient creates a new OperatorGetOperatorGroupsForOperatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOperatorGetOperatorGroupsForOperatorParamsWithHTTPClient(client *http.Client) *OperatorGetOperatorGroupsForOperatorParams {
	var ()
	return &OperatorGetOperatorGroupsForOperatorParams{
		HTTPClient: client,
	}
}

/*OperatorGetOperatorGroupsForOperatorParams contains all the parameters to send to the API endpoint
for the operator get operator groups for operator operation typically these are written to a http.Request
*/
type OperatorGetOperatorGroupsForOperatorParams struct {

	/*OperatorGUID
	  The Guid of the operator for which to retrieve the operator group guids

	*/
	OperatorGUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) WithTimeout(timeout time.Duration) *OperatorGetOperatorGroupsForOperatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) WithContext(ctx context.Context) *OperatorGetOperatorGroupsForOperatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) WithHTTPClient(client *http.Client) *OperatorGetOperatorGroupsForOperatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperatorGUID adds the operatorGUID to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) WithOperatorGUID(operatorGUID string) *OperatorGetOperatorGroupsForOperatorParams {
	o.SetOperatorGUID(operatorGUID)
	return o
}

// SetOperatorGUID adds the operatorGuid to the operator get operator groups for operator params
func (o *OperatorGetOperatorGroupsForOperatorParams) SetOperatorGUID(operatorGUID string) {
	o.OperatorGUID = operatorGUID
}

// WriteToRequest writes these params to a swagger request
func (o *OperatorGetOperatorGroupsForOperatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param operatorGuid
	if err := r.SetPathParam("operatorGuid", o.OperatorGUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
