// Code generated by go-swagger; DO NOT EDIT.

package operator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/damoun/uptrends/models"
)

// NewOperatorUpdateDutyPeriodForOperatorParams creates a new OperatorUpdateDutyPeriodForOperatorParams object
// with the default values initialized.
func NewOperatorUpdateDutyPeriodForOperatorParams() *OperatorUpdateDutyPeriodForOperatorParams {
	var ()
	return &OperatorUpdateDutyPeriodForOperatorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOperatorUpdateDutyPeriodForOperatorParamsWithTimeout creates a new OperatorUpdateDutyPeriodForOperatorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOperatorUpdateDutyPeriodForOperatorParamsWithTimeout(timeout time.Duration) *OperatorUpdateDutyPeriodForOperatorParams {
	var ()
	return &OperatorUpdateDutyPeriodForOperatorParams{

		timeout: timeout,
	}
}

// NewOperatorUpdateDutyPeriodForOperatorParamsWithContext creates a new OperatorUpdateDutyPeriodForOperatorParams object
// with the default values initialized, and the ability to set a context for a request
func NewOperatorUpdateDutyPeriodForOperatorParamsWithContext(ctx context.Context) *OperatorUpdateDutyPeriodForOperatorParams {
	var ()
	return &OperatorUpdateDutyPeriodForOperatorParams{

		Context: ctx,
	}
}

// NewOperatorUpdateDutyPeriodForOperatorParamsWithHTTPClient creates a new OperatorUpdateDutyPeriodForOperatorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOperatorUpdateDutyPeriodForOperatorParamsWithHTTPClient(client *http.Client) *OperatorUpdateDutyPeriodForOperatorParams {
	var ()
	return &OperatorUpdateDutyPeriodForOperatorParams{
		HTTPClient: client,
	}
}

/*OperatorUpdateDutyPeriodForOperatorParams contains all the parameters to send to the API endpoint
for the operator update duty period for operator operation typically these are written to a http.Request
*/
type OperatorUpdateDutyPeriodForOperatorParams struct {

	/*DutyScheduleID*/
	DutyScheduleID int32
	/*OperatorGUID*/
	OperatorGUID string
	/*Schedule*/
	Schedule *models.OperatorDutySchedule

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) WithTimeout(timeout time.Duration) *OperatorUpdateDutyPeriodForOperatorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) WithContext(ctx context.Context) *OperatorUpdateDutyPeriodForOperatorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) WithHTTPClient(client *http.Client) *OperatorUpdateDutyPeriodForOperatorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDutyScheduleID adds the dutyScheduleID to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) WithDutyScheduleID(dutyScheduleID int32) *OperatorUpdateDutyPeriodForOperatorParams {
	o.SetDutyScheduleID(dutyScheduleID)
	return o
}

// SetDutyScheduleID adds the dutyScheduleId to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) SetDutyScheduleID(dutyScheduleID int32) {
	o.DutyScheduleID = dutyScheduleID
}

// WithOperatorGUID adds the operatorGUID to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) WithOperatorGUID(operatorGUID string) *OperatorUpdateDutyPeriodForOperatorParams {
	o.SetOperatorGUID(operatorGUID)
	return o
}

// SetOperatorGUID adds the operatorGuid to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) SetOperatorGUID(operatorGUID string) {
	o.OperatorGUID = operatorGUID
}

// WithSchedule adds the schedule to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) WithSchedule(schedule *models.OperatorDutySchedule) *OperatorUpdateDutyPeriodForOperatorParams {
	o.SetSchedule(schedule)
	return o
}

// SetSchedule adds the schedule to the operator update duty period for operator params
func (o *OperatorUpdateDutyPeriodForOperatorParams) SetSchedule(schedule *models.OperatorDutySchedule) {
	o.Schedule = schedule
}

// WriteToRequest writes these params to a swagger request
func (o *OperatorUpdateDutyPeriodForOperatorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dutyScheduleId
	if err := r.SetPathParam("dutyScheduleId", swag.FormatInt32(o.DutyScheduleID)); err != nil {
		return err
	}

	// path param operatorGuid
	if err := r.SetPathParam("operatorGuid", o.OperatorGUID); err != nil {
		return err
	}

	if o.Schedule != nil {
		if err := r.SetBodyParam(o.Schedule); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
