// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/damoun/uptrends/v4/models"
)

// DashboardGetOneDashboardReader is a Reader for the DashboardGetOneDashboard structure.
type DashboardGetOneDashboardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DashboardGetOneDashboardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDashboardGetOneDashboardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDashboardGetOneDashboardBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDashboardGetOneDashboardNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDashboardGetOneDashboardOK creates a DashboardGetOneDashboardOK with default headers values
func NewDashboardGetOneDashboardOK() *DashboardGetOneDashboardOK {
	return &DashboardGetOneDashboardOK{}
}

/*DashboardGetOneDashboardOK handles this case with default header values.

The request completed successfully.
*/
type DashboardGetOneDashboardOK struct {
	Payload *models.Dashboard
}

func (o *DashboardGetOneDashboardOK) Error() string {
	return fmt.Sprintf("[GET /Dashboard/{dashboardGuid}][%d] dashboardGetOneDashboardOK  %+v", 200, o.Payload)
}

func (o *DashboardGetOneDashboardOK) GetPayload() *models.Dashboard {
	return o.Payload
}

func (o *DashboardGetOneDashboardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dashboard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDashboardGetOneDashboardBadRequest creates a DashboardGetOneDashboardBadRequest with default headers values
func NewDashboardGetOneDashboardBadRequest() *DashboardGetOneDashboardBadRequest {
	return &DashboardGetOneDashboardBadRequest{}
}

/*DashboardGetOneDashboardBadRequest handles this case with default header values.

The request failed.
*/
type DashboardGetOneDashboardBadRequest struct {
	Payload *models.MessageList
}

func (o *DashboardGetOneDashboardBadRequest) Error() string {
	return fmt.Sprintf("[GET /Dashboard/{dashboardGuid}][%d] dashboardGetOneDashboardBadRequest  %+v", 400, o.Payload)
}

func (o *DashboardGetOneDashboardBadRequest) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *DashboardGetOneDashboardBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDashboardGetOneDashboardNotFound creates a DashboardGetOneDashboardNotFound with default headers values
func NewDashboardGetOneDashboardNotFound() *DashboardGetOneDashboardNotFound {
	return &DashboardGetOneDashboardNotFound{}
}

/*DashboardGetOneDashboardNotFound handles this case with default header values.

The specified dashboard could not be found.
*/
type DashboardGetOneDashboardNotFound struct {
	Payload *models.MessageList
}

func (o *DashboardGetOneDashboardNotFound) Error() string {
	return fmt.Sprintf("[GET /Dashboard/{dashboardGuid}][%d] dashboardGetOneDashboardNotFound  %+v", 404, o.Payload)
}

func (o *DashboardGetOneDashboardNotFound) GetPayload() *models.MessageList {
	return o.Payload
}

func (o *DashboardGetOneDashboardNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
