// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ResourceObject15 resource object15
// swagger:model ResourceObject15
type ResourceObject15 struct {
	ResourceObject16
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ResourceObject15) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ResourceObject16
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ResourceObject16 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ResourceObject15) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ResourceObject16)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this resource object15
func (m *ResourceObject15) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResourceObject16
	if err := m.ResourceObject16.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceObject15) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceObject15) UnmarshalBinary(b []byte) error {
	var res ResourceObject15
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
